/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frontend;

/**
 *
 * @author BOG-A307-E-016
 */
public class Frm_inventario extends javax.swing.JFrame {

    /**
     * Creates new form Frm_Pr
     */
    public Frm_inventario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        contrag = new javax.swing.JLabel();
        codigouss = new javax.swing.JTextField();
        codigousg = new javax.swing.JLabel();
        eliminar2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        codigouss1 = new javax.swing.JTextField();
        codigouss2 = new javax.swing.JTextField();
        Correog1 = new javax.swing.JLabel();
        Categoria = new javax.swing.JComboBox<>();
        codigousg1 = new javax.swing.JLabel();
        codigouss3 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        eliminar = new javax.swing.JButton();
        modificar = new javax.swing.JButton();
        guardar = new javax.swing.JButton();
        registro2 = new javax.swing.JLabel();
        primer_registro = new javax.swing.JButton();
        registro = new javax.swing.JButton();
        Correog2 = new javax.swing.JLabel();
        n_registro = new javax.swing.JLabel();
        mod = new javax.swing.JLabel();
        guardar2 = new javax.swing.JLabel();
        guardar3 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        jMenu7 = new javax.swing.JMenu();
        jMenu8 = new javax.swing.JMenu();
        jMenu31 = new javax.swing.JMenu();
        jMenu32 = new javax.swing.JMenu();
        jMenu9 = new javax.swing.JMenu();
        jMenu10 = new javax.swing.JMenu();
        jMenu30 = new javax.swing.JMenu();
        jMenu33 = new javax.swing.JMenu();
        jMenu34 = new javax.swing.JMenu();
        jMenu35 = new javax.swing.JMenu();
        jMenu36 = new javax.swing.JMenu();
        jMenu37 = new javax.swing.JMenu();
        jMenu24 = new javax.swing.JMenu();
        jMenu25 = new javax.swing.JMenu();
        jMenu26 = new javax.swing.JMenu();
        jMenu27 = new javax.swing.JMenu();
        jMenu28 = new javax.swing.JMenu();
        jMenu29 = new javax.swing.JMenu();
        jMenu17 = new javax.swing.JMenu();
        jMenu19 = new javax.swing.JMenu();
        jMenu21 = new javax.swing.JMenu();
        jMenu78 = new javax.swing.JMenu();
        jMenu79 = new javax.swing.JMenu();
        jMenu80 = new javax.swing.JMenu();
        jMenu11 = new javax.swing.JMenu();
        jMenu12 = new javax.swing.JMenu();
        jMenu13 = new javax.swing.JMenu();
        jMenu14 = new javax.swing.JMenu();
        jMenu15 = new javax.swing.JMenu();
        jMenu16 = new javax.swing.JMenu();
        jMenu18 = new javax.swing.JMenu();
        jMenu20 = new javax.swing.JMenu();
        jMenu22 = new javax.swing.JMenu();
        jMenu23 = new javax.swing.JMenu();
        jMenu38 = new javax.swing.JMenu();
        jMenu39 = new javax.swing.JMenu();
        jMenu40 = new javax.swing.JMenu();
        jMenu41 = new javax.swing.JMenu();
        jMenu50 = new javax.swing.JMenu();
        jMenu51 = new javax.swing.JMenu();
        jMenu52 = new javax.swing.JMenu();
        jMenu42 = new javax.swing.JMenu();
        jMenu43 = new javax.swing.JMenu();
        jMenu44 = new javax.swing.JMenu();
        jMenu45 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenu46 = new javax.swing.JMenu();
        jMenu47 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jMenu48 = new javax.swing.JMenu();
        jMenu53 = new javax.swing.JMenu();
        jMenu54 = new javax.swing.JMenu();
        jMenu49 = new javax.swing.JMenu();

        jMenuItem1.setText("jMenuItem1");

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("UD Digi Kyokasho NK-B", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(52, 52, 52));
        jLabel5.setText("Registre los productos");
        jPanel4.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 0, 250, 40));

        contrag.setFont(new java.awt.Font("UD Digi Kyokasho NK-B", 1, 12)); // NOI18N
        contrag.setText("Descripción*");
        jPanel4.add(contrag, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 70, -1, -1));

        codigouss.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codigoussActionPerformed(evt);
            }
        });
        jPanel4.add(codigouss, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 90, 160, 30));

        codigousg.setFont(new java.awt.Font("UD Digi Kyokasho NK-B", 1, 12)); // NOI18N
        codigousg.setText("IVA*");
        jPanel4.add(codigousg, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, -1));

        eliminar2.setFont(new java.awt.Font("UD Digi Kyokasho NK-B", 1, 12)); // NOI18N
        eliminar2.setText("Eliminar");
        jPanel4.add(eliminar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 400, -1, -1));

        jLabel8.setFont(new java.awt.Font("UD Digi Kyokasho NK-B", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(102, 102, 102));
        jLabel8.setText("Complete la información de los productos");
        jPanel4.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 270, -1));

        codigouss1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codigouss1ActionPerformed(evt);
            }
        });
        jPanel4.add(codigouss1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 160, 30));

        codigouss2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codigouss2ActionPerformed(evt);
            }
        });
        jPanel4.add(codigouss2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 90, 160, 30));

        Correog1.setFont(new java.awt.Font("UD Digi Kyokasho NK-B", 1, 12)); // NOI18N
        Correog1.setText("Precio*");
        jPanel4.add(Correog1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 70, -1, -1));

        Categoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        Categoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CategoriaActionPerformed(evt);
            }
        });
        jPanel4.add(Categoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 150, 160, 30));

        codigousg1.setFont(new java.awt.Font("UD Digi Kyokasho NK-B", 1, 12)); // NOI18N
        codigousg1.setText("ID Producto*");
        jPanel4.add(codigousg1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));

        codigouss3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codigouss3ActionPerformed(evt);
            }
        });
        jPanel4.add(codigouss3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 160, 30));

        jTable1.setFont(new java.awt.Font("UD Digi Kyokasho NK-B", 0, 12)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Código", "Producto", "Categoria", "Marca", "Descripción", "Cantidad", "Precio"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel4.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 560, 80));

        eliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img3/eliminar.png"))); // NOI18N
        eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarActionPerformed(evt);
            }
        });
        jPanel4.add(eliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 320, 80, 70));

        modificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img3/modificar.png"))); // NOI18N
        modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarActionPerformed(evt);
            }
        });
        jPanel4.add(modificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 320, 90, 70));

        guardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img3/guardar.png"))); // NOI18N
        guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarActionPerformed(evt);
            }
        });
        jPanel4.add(guardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 320, 80, 80));

        registro2.setFont(new java.awt.Font("UD Digi Kyokasho NK-B", 1, 12)); // NOI18N
        registro2.setText("Registro");
        jPanel4.add(registro2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 400, -1, -1));

        primer_registro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img3/primer_registro.png"))); // NOI18N
        primer_registro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                primer_registroActionPerformed(evt);
            }
        });
        jPanel4.add(primer_registro, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 320, 80, 80));

        registro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img3/registro.png"))); // NOI18N
        registro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registroActionPerformed(evt);
            }
        });
        jPanel4.add(registro, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, 60, 70));

        Correog2.setFont(new java.awt.Font("UD Digi Kyokasho NK-B", 1, 12)); // NOI18N
        Correog2.setText("Categoria*");
        jPanel4.add(Correog2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 130, -1, -1));

        n_registro.setFont(new java.awt.Font("UD Digi Kyokasho NK-B", 1, 12)); // NOI18N
        n_registro.setText("Nuevo Registro");
        jPanel4.add(n_registro, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 400, -1, -1));

        mod.setFont(new java.awt.Font("UD Digi Kyokasho NK-B", 1, 12)); // NOI18N
        mod.setText("Modificar");
        jPanel4.add(mod, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 400, -1, -1));

        guardar2.setFont(new java.awt.Font("UD Digi Kyokasho NK-B", 1, 12)); // NOI18N
        guardar2.setText("Actualizar");
        jPanel4.add(guardar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 400, -1, -1));

        guardar3.setFont(new java.awt.Font("UD Digi Kyokasho NK-B", 1, 12)); // NOI18N
        guardar3.setText("Guardar");
        jPanel4.add(guardar3, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 400, -1, -1));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 170, 610, 430));

        jButton3.setFont(new java.awt.Font("UD Digi Kyokasho NK-B", 0, 12)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img2/Villa_Home_Icon_UIA.png"))); // NOI18N
        jButton3.setText("Inicio");
        jButton3.setBorder(null);
        jButton3.setContentAreaFilled(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 20, 120, 30));

        jButton2.setFont(new java.awt.Font("UD Digi Kyokasho NK-B", 0, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img2/Cart_Icon_UIA.png"))); // NOI18N
        jButton2.setText("Tienda");
        jButton2.setBorder(null);
        jButton2.setContentAreaFilled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 20, 120, 30));

        jButton5.setFont(new java.awt.Font("UD Digi Kyokasho NK-B", 0, 12)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img2/profile-circle.png"))); // NOI18N
        jButton5.setText("Login");
        jButton5.setBorder(null);
        jButton5.setContentAreaFilled(false);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 20, 120, 30));

        jButton6.setFont(new java.awt.Font("UD Digi Kyokasho NK-B", 0, 12)); // NOI18N
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img2/call.png"))); // NOI18N
        jButton6.setText("Contactenos");
        jButton6.setBorder(null);
        jButton6.setContentAreaFilled(false);
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 20, 120, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Logo.jpg"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Form2.png"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, 1020, 530));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Vector2.png"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(-130, 0, 1330, 180));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 1100, 720));

        jMenuBar1.setBorder(null);
        jMenuBar1.setFont(new java.awt.Font("UD Digi Kyokasho NK-B", 1, 12)); // NOI18N

        jMenu2.setText("Inicio");
        jMenu2.setFont(new java.awt.Font("UD Digi Kyokasho NK-B", 1, 12)); // NOI18N
        jMenuBar1.add(jMenu2);

        jMenu3.setText("Tienda");
        jMenu3.setFont(new java.awt.Font("UD Digi Kyokasho NK-B", 1, 12)); // NOI18N

        jMenu6.setText("Tecnologia");
        jMenu6.setFont(new java.awt.Font("UD Digi Kyokasho NK-B", 1, 12)); // NOI18N

        jMenu7.setText("Ordenadores");
        jMenu7.setFocusable(false);
        jMenu7.setFont(new java.awt.Font("UD Digi Kyokasho NK-B", 1, 12)); // NOI18N

        jMenu8.setText("Portatiles");
        jMenu8.setFont(new java.awt.Font("UD Digi Kyokasho NK-B", 1, 12)); // NOI18N

        jMenu31.setText("Gaming");
        jMenu31.setFont(new java.awt.Font("UD Digi Kyokasho NK-B", 1, 12)); // NOI18N
        jMenu8.add(jMenu31);

        jMenu32.setText("Baratos");
        jMenu32.setFont(new java.awt.Font("UD Digi Kyokasho NK-B", 1, 12)); // NOI18N
        jMenu8.add(jMenu32);

        jMenu7.add(jMenu8);

        jMenu9.setText("PC sobre mesa");
        jMenu9.setFont(new java.awt.Font("UD Digi Kyokasho NK-B", 1, 12)); // NOI18N

        jMenu10.setText("PC gaming");
        jMenu10.setFont(new java.awt.Font("UD Digi Kyokasho NK-B", 1, 12)); // NOI18N
        jMenu9.add(jMenu10);

        jMenu30.setText("PC todo en uno");
        jMenu30.setFont(new java.awt.Font("UD Digi Kyokasho NK-B", 1, 12)); // NOI18N
        jMenu9.add(jMenu30);

        jMenu7.add(jMenu9);

        jMenu33.setText("Por marca");
        jMenu33.setFont(new java.awt.Font("UD Digi Kyokasho NK-B", 1, 12)); // NOI18N

        jMenu34.setText("Hp");
        jMenu34.setFont(new java.awt.Font("UD Digi Kyokasho NK-B", 1, 12)); // NOI18N
        jMenu33.add(jMenu34);

        jMenu35.setText("Lenovo");
        jMenu35.setFont(new java.awt.Font("UD Digi Kyokasho NK-B", 1, 12)); // NOI18N
        jMenu33.add(jMenu35);

        jMenu36.setText("Asus");
        jMenu36.setFont(new java.awt.Font("UD Digi Kyokasho NK-B", 1, 12)); // NOI18N
        jMenu33.add(jMenu36);

        jMenu37.setText("Acer");
        jMenu37.setFont(new java.awt.Font("UD Digi Kyokasho NK-B", 1, 12)); // NOI18N
        jMenu33.add(jMenu37);

        jMenu7.add(jMenu33);

        jMenu6.add(jMenu7);

        jMenu24.setText("Componentes");
        jMenu24.setFont(new java.awt.Font("UD Digi Kyokasho NK-B", 1, 12)); // NOI18N

        jMenu25.setText("Placas base");
        jMenu25.setFocusable(false);
        jMenu25.setFont(new java.awt.Font("UD Digi Kyokasho NK-B", 1, 12)); // NOI18N
        jMenu24.add(jMenu25);

        jMenu26.setText("Procesadores");
        jMenu26.setFocusable(false);
        jMenu26.setFont(new java.awt.Font("UD Digi Kyokasho NK-B", 1, 12)); // NOI18N
        jMenu24.add(jMenu26);

        jMenu27.setText("Discos duros");
        jMenu27.setFocusable(false);
        jMenu27.setFont(new java.awt.Font("UD Digi Kyokasho NK-B", 1, 12)); // NOI18N
        jMenu24.add(jMenu27);

        jMenu28.setText("Tarjetas gráficas");
        jMenu28.setFocusable(false);
        jMenu28.setFont(new java.awt.Font("UD Digi Kyokasho NK-B", 1, 12)); // NOI18N
        jMenu24.add(jMenu28);

        jMenu29.setText("Memoria RAM");
        jMenu29.setFocusable(false);
        jMenu29.setFont(new java.awt.Font("UD Digi Kyokasho NK-B", 1, 12)); // NOI18N
        jMenu24.add(jMenu29);

        jMenu6.add(jMenu24);

        jMenu17.setText("Perifericos");
        jMenu17.setFont(new java.awt.Font("UD Digi Kyokasho NK-B", 1, 12)); // NOI18N

        jMenu19.setText("Monitores");
        jMenu19.setFocusable(false);
        jMenu19.setFont(new java.awt.Font("UD Digi Kyokasho NK-B", 1, 12)); // NOI18N
        jMenu17.add(jMenu19);

        jMenu21.setText("Teclados");
        jMenu21.setFocusable(false);
        jMenu21.setFont(new java.awt.Font("UD Digi Kyokasho NK-B", 1, 12)); // NOI18N
        jMenu17.add(jMenu21);

        jMenu78.setText("Ratones");
        jMenu78.setFocusable(false);
        jMenu78.setFont(new java.awt.Font("UD Digi Kyokasho NK-B", 1, 12)); // NOI18N
        jMenu17.add(jMenu78);

        jMenu79.setText("Auriculares");
        jMenu79.setFocusable(false);
        jMenu79.setFont(new java.awt.Font("UD Digi Kyokasho NK-B", 1, 12)); // NOI18N
        jMenu17.add(jMenu79);

        jMenu80.setText("Microfonos");
        jMenu80.setFocusable(false);
        jMenu80.setFont(new java.awt.Font("UD Digi Kyokasho NK-B", 1, 12)); // NOI18N
        jMenu17.add(jMenu80);

        jMenu6.add(jMenu17);

        jMenu11.setText("Almacenamiento");
        jMenu11.setFocusable(false);
        jMenu11.setFont(new java.awt.Font("UD Digi Kyokasho NK-B", 1, 12)); // NOI18N

        jMenu12.setText("Memorias USB");
        jMenu12.setFont(new java.awt.Font("UD Digi Kyokasho NK-B", 1, 12)); // NOI18N
        jMenu11.add(jMenu12);

        jMenu13.setText("Tarjetas de memoria");
        jMenu13.setFont(new java.awt.Font("UD Digi Kyokasho NK-B", 1, 12)); // NOI18N
        jMenu11.add(jMenu13);

        jMenu14.setText("Discos duros");
        jMenu14.setFont(new java.awt.Font("UD Digi Kyokasho NK-B", 1, 12)); // NOI18N
        jMenu11.add(jMenu14);

        jMenu6.add(jMenu11);

        jMenu15.setText("Cables");
        jMenu15.setFont(new java.awt.Font("UD Digi Kyokasho NK-B", 1, 12)); // NOI18N

        jMenu16.setText("Adaptadores");
        jMenu16.setFocusable(false);
        jMenu16.setFont(new java.awt.Font("UD Digi Kyokasho NK-B", 1, 12)); // NOI18N
        jMenu15.add(jMenu16);

        jMenu18.setText("Cables audio/video");
        jMenu18.setFocusable(false);
        jMenu18.setFont(new java.awt.Font("UD Digi Kyokasho NK-B", 1, 12)); // NOI18N
        jMenu15.add(jMenu18);

        jMenu20.setText("Cables HDMI");
        jMenu20.setFocusable(false);
        jMenu20.setFont(new java.awt.Font("UD Digi Kyokasho NK-B", 1, 12)); // NOI18N
        jMenu15.add(jMenu20);

        jMenu22.setText("Cables VGA");
        jMenu22.setFocusable(false);
        jMenu22.setFont(new java.awt.Font("UD Digi Kyokasho NK-B", 1, 12)); // NOI18N
        jMenu15.add(jMenu22);

        jMenu23.setText("Cables USB");
        jMenu23.setFocusable(false);
        jMenu23.setFont(new java.awt.Font("UD Digi Kyokasho NK-B", 1, 12)); // NOI18N
        jMenu15.add(jMenu23);

        jMenu6.add(jMenu15);

        jMenu3.add(jMenu6);

        jMenu38.setText("Ferreteria");
        jMenu38.setFocusable(false);
        jMenu38.setFont(new java.awt.Font("UD Digi Kyokasho NK-B", 1, 12)); // NOI18N

        jMenu39.setText("Herramientas");
        jMenu39.setFont(new java.awt.Font("UD Digi Kyokasho NK-B", 1, 12)); // NOI18N

        jMenu40.setText("Taladros");
        jMenu40.setFont(new java.awt.Font("UD Digi Kyokasho NK-B", 1, 12)); // NOI18N
        jMenu39.add(jMenu40);

        jMenu41.setText("Martillos perforadores");
        jMenu41.setFont(new java.awt.Font("UD Digi Kyokasho NK-B", 1, 12)); // NOI18N
        jMenu39.add(jMenu41);

        jMenu50.setText("Atornilladores");
        jMenu50.setFont(new java.awt.Font("UD Digi Kyokasho NK-B", 1, 12)); // NOI18N
        jMenu39.add(jMenu50);

        jMenu51.setText("Destornilladores electricos");
        jMenu51.setFont(new java.awt.Font("UD Digi Kyokasho NK-B", 1, 12)); // NOI18N
        jMenu39.add(jMenu51);

        jMenu52.setText("Kits de herramientas");
        jMenu52.setFont(new java.awt.Font("UD Digi Kyokasho NK-B", 1, 12)); // NOI18N
        jMenu39.add(jMenu52);

        jMenu38.add(jMenu39);

        jMenu42.setText("De estructura");
        jMenu42.setFont(new java.awt.Font("UD Digi Kyokasho NK-B", 1, 12)); // NOI18N

        jMenu43.setText("Anclajes");
        jMenu43.setFont(new java.awt.Font("UD Digi Kyokasho NK-B", 1, 12)); // NOI18N
        jMenu42.add(jMenu43);

        jMenu44.setText("Perfiles");
        jMenu44.setFont(new java.awt.Font("UD Digi Kyokasho NK-B", 1, 12)); // NOI18N
        jMenu42.add(jMenu44);

        jMenu45.setText("Soporte");
        jMenu45.setFont(new java.awt.Font("UD Digi Kyokasho NK-B", 1, 12)); // NOI18N
        jMenu42.add(jMenu45);

        jMenu38.add(jMenu42);

        jMenu3.add(jMenu38);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Contactenos");
        jMenu4.setFont(new java.awt.Font("UD Digi Kyokasho NK-B", 1, 12)); // NOI18N

        jMenu46.setText("Sobre nosotros");
        jMenu46.setFont(new java.awt.Font("UD Digi Kyokasho NK-B", 1, 12)); // NOI18N
        jMenu4.add(jMenu46);

        jMenu47.setText("Detalles de contacto");
        jMenu47.setFont(new java.awt.Font("UD Digi Kyokasho NK-B", 1, 12)); // NOI18N
        jMenu4.add(jMenu47);

        jMenuBar1.add(jMenu4);

        jMenu5.setText("Login");
        jMenu5.setFont(new java.awt.Font("UD Digi Kyokasho NK-B", 1, 12)); // NOI18N

        jMenu48.setText("Unetenos");
        jMenu48.setFont(new java.awt.Font("UD Digi Kyokasho NK-B", 1, 12)); // NOI18N

        jMenu53.setText("Como vendedor");
        jMenu53.setFont(new java.awt.Font("UD Digi Kyokasho NK-B", 1, 12)); // NOI18N
        jMenu48.add(jMenu53);

        jMenu54.setText("Como cliente");
        jMenu54.setFont(new java.awt.Font("UD Digi Kyokasho NK-B", 1, 12)); // NOI18N
        jMenu48.add(jMenu54);

        jMenu5.add(jMenu48);

        jMenu49.setText("Inicia sesión");
        jMenu49.setFont(new java.awt.Font("UD Digi Kyokasho NK-B", 1, 12)); // NOI18N
        jMenu5.add(jMenu49);

        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void codigoussActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codigoussActionPerformed
    
    }//GEN-LAST:event_codigoussActionPerformed

    private void codigouss1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codigouss1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_codigouss1ActionPerformed

    private void codigouss2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codigouss2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_codigouss2ActionPerformed

    private void codigouss3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codigouss3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_codigouss3ActionPerformed

    private void eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_eliminarActionPerformed

    private void modificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_modificarActionPerformed

    private void guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_guardarActionPerformed

    private void primer_registroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_primer_registroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_primer_registroActionPerformed

    private void registroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_registroActionPerformed

    private void CategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CategoriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CategoriaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frm_inventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frm_inventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frm_inventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frm_inventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frm_inventario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Categoria;
    private javax.swing.JLabel Correog1;
    private javax.swing.JLabel Correog2;
    private javax.swing.JLabel codigousg;
    private javax.swing.JLabel codigousg1;
    private javax.swing.JTextField codigouss;
    private javax.swing.JTextField codigouss1;
    private javax.swing.JTextField codigouss2;
    private javax.swing.JTextField codigouss3;
    private javax.swing.JLabel contrag;
    private javax.swing.JButton eliminar;
    private javax.swing.JLabel eliminar2;
    private javax.swing.JButton guardar;
    private javax.swing.JLabel guardar2;
    private javax.swing.JLabel guardar3;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu10;
    private javax.swing.JMenu jMenu11;
    private javax.swing.JMenu jMenu12;
    private javax.swing.JMenu jMenu13;
    private javax.swing.JMenu jMenu14;
    private javax.swing.JMenu jMenu15;
    private javax.swing.JMenu jMenu16;
    private javax.swing.JMenu jMenu17;
    private javax.swing.JMenu jMenu18;
    private javax.swing.JMenu jMenu19;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu20;
    private javax.swing.JMenu jMenu21;
    private javax.swing.JMenu jMenu22;
    private javax.swing.JMenu jMenu23;
    private javax.swing.JMenu jMenu24;
    private javax.swing.JMenu jMenu25;
    private javax.swing.JMenu jMenu26;
    private javax.swing.JMenu jMenu27;
    private javax.swing.JMenu jMenu28;
    private javax.swing.JMenu jMenu29;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu30;
    private javax.swing.JMenu jMenu31;
    private javax.swing.JMenu jMenu32;
    private javax.swing.JMenu jMenu33;
    private javax.swing.JMenu jMenu34;
    private javax.swing.JMenu jMenu35;
    private javax.swing.JMenu jMenu36;
    private javax.swing.JMenu jMenu37;
    private javax.swing.JMenu jMenu38;
    private javax.swing.JMenu jMenu39;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu40;
    private javax.swing.JMenu jMenu41;
    private javax.swing.JMenu jMenu42;
    private javax.swing.JMenu jMenu43;
    private javax.swing.JMenu jMenu44;
    private javax.swing.JMenu jMenu45;
    private javax.swing.JMenu jMenu46;
    private javax.swing.JMenu jMenu47;
    private javax.swing.JMenu jMenu48;
    private javax.swing.JMenu jMenu49;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu50;
    private javax.swing.JMenu jMenu51;
    private javax.swing.JMenu jMenu52;
    private javax.swing.JMenu jMenu53;
    private javax.swing.JMenu jMenu54;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu78;
    private javax.swing.JMenu jMenu79;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenu jMenu80;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel mod;
    private javax.swing.JButton modificar;
    private javax.swing.JLabel n_registro;
    private javax.swing.JButton primer_registro;
    private javax.swing.JButton registro;
    private javax.swing.JLabel registro2;
    // End of variables declaration//GEN-END:variables
}
