/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frontend;

/**
 *
 * @author USER
 */
public class Producto extends javax.swing.JFrame {

    /**
     * Creates new form Tienda
     */
    public Producto() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jSpinner2 = new javax.swing.JSpinner();
        jButton13 = new javax.swing.JButton();
        jLabel30 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jComboBox3 = new javax.swing.JComboBox<>();
        jButton14 = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        jMenu7 = new javax.swing.JMenu();
        jMenu8 = new javax.swing.JMenu();
        jMenu31 = new javax.swing.JMenu();
        jMenu32 = new javax.swing.JMenu();
        jMenu9 = new javax.swing.JMenu();
        jMenu10 = new javax.swing.JMenu();
        jMenu30 = new javax.swing.JMenu();
        jMenu33 = new javax.swing.JMenu();
        jMenu34 = new javax.swing.JMenu();
        jMenu35 = new javax.swing.JMenu();
        jMenu36 = new javax.swing.JMenu();
        jMenu37 = new javax.swing.JMenu();
        jMenu24 = new javax.swing.JMenu();
        jMenu25 = new javax.swing.JMenu();
        jMenu26 = new javax.swing.JMenu();
        jMenu27 = new javax.swing.JMenu();
        jMenu28 = new javax.swing.JMenu();
        jMenu29 = new javax.swing.JMenu();
        jMenu17 = new javax.swing.JMenu();
        jMenu19 = new javax.swing.JMenu();
        jMenu21 = new javax.swing.JMenu();
        jMenu78 = new javax.swing.JMenu();
        jMenu79 = new javax.swing.JMenu();
        jMenu80 = new javax.swing.JMenu();
        jMenu11 = new javax.swing.JMenu();
        jMenu12 = new javax.swing.JMenu();
        jMenu13 = new javax.swing.JMenu();
        jMenu14 = new javax.swing.JMenu();
        jMenu15 = new javax.swing.JMenu();
        jMenu16 = new javax.swing.JMenu();
        jMenu18 = new javax.swing.JMenu();
        jMenu20 = new javax.swing.JMenu();
        jMenu22 = new javax.swing.JMenu();
        jMenu23 = new javax.swing.JMenu();
        jMenu38 = new javax.swing.JMenu();
        jMenu39 = new javax.swing.JMenu();
        jMenu40 = new javax.swing.JMenu();
        jMenu41 = new javax.swing.JMenu();
        jMenu50 = new javax.swing.JMenu();
        jMenu51 = new javax.swing.JMenu();
        jMenu52 = new javax.swing.JMenu();
        jMenu42 = new javax.swing.JMenu();
        jMenu43 = new javax.swing.JMenu();
        jMenu44 = new javax.swing.JMenu();
        jMenu45 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenu46 = new javax.swing.JMenu();
        jMenu47 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jMenu48 = new javax.swing.JMenu();
        jMenu53 = new javax.swing.JMenu();
        jMenu54 = new javax.swing.JMenu();
        jMenu49 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton3.setBackground(new java.awt.Color(255, 255, 255));
        jButton3.setFont(new java.awt.Font("UD Digi Kyokasho NK-B", 0, 12)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img2/Villa_Home_Icon_UIA.png"))); // NOI18N
        jButton3.setText("Inicio");
        jButton3.setBorder(null);
        jButton3.setContentAreaFilled(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 30, 120, 30));

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setFont(new java.awt.Font("UD Digi Kyokasho NK-B", 0, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img2/Cart_Icon_UIA.png"))); // NOI18N
        jButton2.setText("Tienda");
        jButton2.setBorder(null);
        jButton2.setContentAreaFilled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 30, 120, 30));

        jButton5.setBackground(new java.awt.Color(255, 255, 255));
        jButton5.setFont(new java.awt.Font("UD Digi Kyokasho NK-B", 0, 12)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img2/profile-circle.png"))); // NOI18N
        jButton5.setText("Login");
        jButton5.setBorder(null);
        jButton5.setContentAreaFilled(false);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 30, 120, 30));

        jButton6.setBackground(new java.awt.Color(255, 255, 255));
        jButton6.setFont(new java.awt.Font("UD Digi Kyokasho NK-B", 0, 12)); // NOI18N
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img2/call.png"))); // NOI18N
        jButton6.setText("Contactenos");
        jButton6.setBorder(null);
        jButton6.setContentAreaFilled(false);
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 30, 120, 30));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setForeground(new java.awt.Color(204, 204, 204));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel17.setBackground(new java.awt.Color(255, 255, 255));
        jLabel17.setFont(new java.awt.Font("UD Digi Kyokasho NK-B", 1, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(51, 51, 51));
        jLabel17.setText("Detalles del producto");
        jPanel2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 210, 40));

        jLabel29.setBackground(new java.awt.Color(255, 255, 255));
        jLabel29.setFont(new java.awt.Font("UD Digi Kyokasho NK-B", 1, 14)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(102, 102, 102));
        jLabel29.setText("Nombre: taladro de impacto eléctrico");
        jPanel2.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 290, 40));

        jLabel28.setBackground(new java.awt.Color(255, 255, 255));
        jLabel28.setFont(new java.awt.Font("UD Digi Kyokasho NK-B", 1, 14)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(102, 102, 102));
        jLabel28.setText("Modelo: F63625");
        jPanel2.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 290, 40));

        jLabel31.setBackground(new java.awt.Color(255, 255, 255));
        jLabel31.setFont(new java.awt.Font("UD Digi Kyokasho NK-B", 1, 14)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(102, 102, 102));
        jLabel31.setText("Especificaciones");
        jPanel2.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 290, 20));

        jLabel32.setBackground(new java.awt.Color(255, 255, 255));
        jLabel32.setFont(new java.awt.Font("UD Digi Kyokasho NK-B", 1, 14)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(153, 153, 153));
        jLabel32.setText("Voltaje: 220 V");
        jPanel2.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 140, 20));

        jLabel33.setBackground(new java.awt.Color(255, 255, 255));
        jLabel33.setFont(new java.awt.Font("UD Digi Kyokasho NK-B", 1, 14)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(153, 153, 153));
        jLabel33.setText("Poder: 1980W");
        jPanel2.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 140, 20));

        jLabel24.setBackground(new java.awt.Color(255, 255, 255));
        jLabel24.setFont(new java.awt.Font("UD Digi Kyokasho NK-B", 1, 14)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(153, 153, 153));
        jLabel24.setText("Garantía 2 años");
        jPanel2.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 260, 20));

        jLabel35.setBackground(new java.awt.Color(255, 255, 255));
        jLabel35.setFont(new java.awt.Font("UD Digi Kyokasho NK-B", 1, 14)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(153, 153, 153));
        jLabel35.setText("Frecuencia nominal: 50/60 Hz");
        jPanel2.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 260, 20));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 610, 320, 220));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Logo.jpg"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, -1));

        jLabel20.setBackground(new java.awt.Color(255, 255, 255));
        jLabel20.setFont(new java.awt.Font("UD Digi Kyokasho NK-B", 1, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(64, 82, 174));
        jLabel20.setText("(Herramienta Poderosa de Ferretería)");
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 210, 490, 40));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Vector2.png"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(-100, -10, -1, 230));

        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img2/Taladro_Percutor3.png"))); // NOI18N
        jButton7.setBorder(null);
        jButton7.setBorderPainted(false);
        jButton7.setContentAreaFilled(false);
        jButton7.setDefaultCapable(false);
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 250, 140, 130));

        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img2/Taladro_Percutor.png"))); // NOI18N
        jButton8.setBorder(null);
        jButton8.setBorderPainted(false);
        jButton8.setContentAreaFilled(false);
        jButton8.setDefaultCapable(false);
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 370, 360, 250));

        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img2/Taladro_Percutor1.png"))); // NOI18N
        jButton9.setBorder(null);
        jButton9.setBorderPainted(false);
        jButton9.setContentAreaFilled(false);
        jButton9.setDefaultCapable(false);
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 250, 140, 130));

        jButton10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img2/Taladro_Percutor2.png"))); // NOI18N
        jButton10.setBorder(null);
        jButton10.setBorderPainted(false);
        jButton10.setContentAreaFilled(false);
        jButton10.setDefaultCapable(false);
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 250, 140, 130));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setForeground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel26.setBackground(new java.awt.Color(255, 255, 255));
        jLabel26.setFont(new java.awt.Font("UD Digi Kyokasho NK-B", 1, 24)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(52, 52, 52));
        jLabel26.setText("$295,899,00");
        jPanel3.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 210, 40));

        jLabel27.setBackground(new java.awt.Color(255, 255, 255));
        jLabel27.setFont(new java.awt.Font("UD Digi Kyokasho NK-B", 1, 14)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(102, 102, 102));
        jLabel27.setText("Antes $305,873,00");
        jPanel3.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 210, 40));
        jPanel3.add(jSpinner2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, 130, -1));

        jButton13.setBackground(new java.awt.Color(64, 82, 174));
        jButton13.setFont(new java.awt.Font("UD Digi Kyokasho NK-B", 0, 12)); // NOI18N
        jButton13.setForeground(new java.awt.Color(255, 255, 255));
        jButton13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Bolsa.png"))); // NOI18N
        jButton13.setText("Añadir a la bolsa");
        jButton13.setBorder(null);
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 250, 30));

        jLabel30.setBackground(new java.awt.Color(255, 255, 255));
        jLabel30.setFont(new java.awt.Font("UD Digi Kyokasho NK-B", 1, 14)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(64, 82, 174));
        jLabel30.setText("Cantidad");
        jPanel3.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 80, 40));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 220, 250, -1));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setForeground(new java.awt.Color(204, 204, 204));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel21.setBackground(new java.awt.Color(255, 255, 255));
        jLabel21.setFont(new java.awt.Font("UD Digi Kyokasho NK-B", 1, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(102, 102, 102));
        jLabel21.setText("Forma de pago");
        jPanel4.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 150, 40));
        jPanel4.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 50, 140, -1));

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel4.add(jComboBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 80, 100, 30));

        jButton14.setBackground(new java.awt.Color(64, 82, 174));
        jButton14.setFont(new java.awt.Font("UD Digi Kyokasho NK-B", 0, 12)); // NOI18N
        jButton14.setForeground(new java.awt.Color(255, 255, 255));
        jButton14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Entrega.png"))); // NOI18N
        jButton14.setText("Entrega");
        jButton14.setBorder(null);
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 250, 30));

        jLabel22.setBackground(new java.awt.Color(255, 255, 255));
        jLabel22.setFont(new java.awt.Font("UD Digi Kyokasho NK-B", 1, 18)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(51, 51, 51));
        jLabel22.setText("Detalles de entrega");
        jPanel4.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 210, 40));

        jLabel34.setBackground(new java.awt.Color(255, 255, 255));
        jLabel34.setFont(new java.awt.Font("UD Digi Kyokasho NK-B", 1, 14)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(102, 102, 102));
        jLabel34.setText("Dirección");
        jPanel4.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 70, 40));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 400, 250, -1));

        jLabel23.setBackground(new java.awt.Color(255, 255, 255));
        jLabel23.setFont(new java.awt.Font("UD Digi Kyokasho NK-B", 1, 18)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(52, 52, 52));
        jLabel23.setText("1980W 3800rmp Taladro Percutor Multifucional");
        jPanel1.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 180, 490, 40));

        jScrollPane1.setViewportView(jPanel1);

        jMenuBar1.setBackground(new java.awt.Color(51, 51, 51));
        jMenuBar1.setBorder(null);
        jMenuBar1.setFont(new java.awt.Font("UD Digi Kyokasho NK-B", 1, 12)); // NOI18N

        jMenu2.setText("Inicio");
        jMenu2.setFont(new java.awt.Font("UD Digi Kyokasho NK-B", 1, 12)); // NOI18N
        jMenuBar1.add(jMenu2);

        jMenu3.setText("Tienda");
        jMenu3.setFont(new java.awt.Font("UD Digi Kyokasho NK-B", 1, 12)); // NOI18N

        jMenu6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img2/cpu.png"))); // NOI18N
        jMenu6.setText("Tecnologia");
        jMenu6.setFont(new java.awt.Font("UD Digi Kyokasho NK-B", 1, 12)); // NOI18N

        jMenu7.setText("Ordenadores");
        jMenu7.setFocusable(false);
        jMenu7.setFont(new java.awt.Font("UD Digi Kyokasho NK-B", 1, 12)); // NOI18N

        jMenu8.setText("Portatiles");
        jMenu8.setFont(new java.awt.Font("UD Digi Kyokasho NK-B", 1, 12)); // NOI18N

        jMenu31.setText("Gaming");
        jMenu31.setFont(new java.awt.Font("UD Digi Kyokasho NK-B", 1, 12)); // NOI18N
        jMenu8.add(jMenu31);

        jMenu32.setText("Baratos");
        jMenu32.setFont(new java.awt.Font("UD Digi Kyokasho NK-B", 1, 12)); // NOI18N
        jMenu8.add(jMenu32);

        jMenu7.add(jMenu8);

        jMenu9.setText("PC sobre mesa");
        jMenu9.setFont(new java.awt.Font("UD Digi Kyokasho NK-B", 1, 12)); // NOI18N

        jMenu10.setText("PC gaming");
        jMenu10.setFont(new java.awt.Font("UD Digi Kyokasho NK-B", 1, 12)); // NOI18N
        jMenu9.add(jMenu10);

        jMenu30.setText("PC todo en uno");
        jMenu30.setFont(new java.awt.Font("UD Digi Kyokasho NK-B", 1, 12)); // NOI18N
        jMenu9.add(jMenu30);

        jMenu7.add(jMenu9);

        jMenu33.setText("Por marca");
        jMenu33.setFont(new java.awt.Font("UD Digi Kyokasho NK-B", 1, 12)); // NOI18N

        jMenu34.setText("Hp");
        jMenu34.setFont(new java.awt.Font("UD Digi Kyokasho NK-B", 1, 12)); // NOI18N
        jMenu33.add(jMenu34);

        jMenu35.setText("Lenovo");
        jMenu35.setFont(new java.awt.Font("UD Digi Kyokasho NK-B", 1, 12)); // NOI18N
        jMenu33.add(jMenu35);

        jMenu36.setText("Asus");
        jMenu36.setFont(new java.awt.Font("UD Digi Kyokasho NK-B", 1, 12)); // NOI18N
        jMenu33.add(jMenu36);

        jMenu37.setText("Acer");
        jMenu37.setFont(new java.awt.Font("UD Digi Kyokasho NK-B", 1, 12)); // NOI18N
        jMenu33.add(jMenu37);

        jMenu7.add(jMenu33);

        jMenu6.add(jMenu7);

        jMenu24.setText("Componentes");
        jMenu24.setFont(new java.awt.Font("UD Digi Kyokasho NK-B", 1, 12)); // NOI18N

        jMenu25.setText("Placas base");
        jMenu25.setFocusable(false);
        jMenu25.setFont(new java.awt.Font("UD Digi Kyokasho NK-B", 1, 12)); // NOI18N
        jMenu24.add(jMenu25);

        jMenu26.setText("Procesadores");
        jMenu26.setFocusable(false);
        jMenu26.setFont(new java.awt.Font("UD Digi Kyokasho NK-B", 1, 12)); // NOI18N
        jMenu24.add(jMenu26);

        jMenu27.setText("Discos duros");
        jMenu27.setFocusable(false);
        jMenu27.setFont(new java.awt.Font("UD Digi Kyokasho NK-B", 1, 12)); // NOI18N
        jMenu24.add(jMenu27);

        jMenu28.setText("Tarjetas gráficas");
        jMenu28.setFocusable(false);
        jMenu28.setFont(new java.awt.Font("UD Digi Kyokasho NK-B", 1, 12)); // NOI18N
        jMenu24.add(jMenu28);

        jMenu29.setText("Memoria RAM");
        jMenu29.setFocusable(false);
        jMenu29.setFont(new java.awt.Font("UD Digi Kyokasho NK-B", 1, 12)); // NOI18N
        jMenu24.add(jMenu29);

        jMenu6.add(jMenu24);

        jMenu17.setText("Perifericos");
        jMenu17.setFont(new java.awt.Font("UD Digi Kyokasho NK-B", 1, 12)); // NOI18N

        jMenu19.setText("Monitores");
        jMenu19.setFocusable(false);
        jMenu19.setFont(new java.awt.Font("UD Digi Kyokasho NK-B", 1, 12)); // NOI18N
        jMenu17.add(jMenu19);

        jMenu21.setText("Teclados");
        jMenu21.setFocusable(false);
        jMenu21.setFont(new java.awt.Font("UD Digi Kyokasho NK-B", 1, 12)); // NOI18N
        jMenu17.add(jMenu21);

        jMenu78.setText("Ratones");
        jMenu78.setFocusable(false);
        jMenu78.setFont(new java.awt.Font("UD Digi Kyokasho NK-B", 1, 12)); // NOI18N
        jMenu17.add(jMenu78);

        jMenu79.setText("Auriculares");
        jMenu79.setFocusable(false);
        jMenu79.setFont(new java.awt.Font("UD Digi Kyokasho NK-B", 1, 12)); // NOI18N
        jMenu17.add(jMenu79);

        jMenu80.setText("Microfonos");
        jMenu80.setFocusable(false);
        jMenu80.setFont(new java.awt.Font("UD Digi Kyokasho NK-B", 1, 12)); // NOI18N
        jMenu17.add(jMenu80);

        jMenu6.add(jMenu17);

        jMenu11.setText("Almacenamiento");
        jMenu11.setFocusable(false);
        jMenu11.setFont(new java.awt.Font("UD Digi Kyokasho NK-B", 1, 12)); // NOI18N

        jMenu12.setText("Memorias USB");
        jMenu12.setFont(new java.awt.Font("UD Digi Kyokasho NK-B", 1, 12)); // NOI18N
        jMenu11.add(jMenu12);

        jMenu13.setText("Tarjetas de memoria");
        jMenu13.setFont(new java.awt.Font("UD Digi Kyokasho NK-B", 1, 12)); // NOI18N
        jMenu11.add(jMenu13);

        jMenu14.setText("Discos duros");
        jMenu14.setFont(new java.awt.Font("UD Digi Kyokasho NK-B", 1, 12)); // NOI18N
        jMenu11.add(jMenu14);

        jMenu6.add(jMenu11);

        jMenu15.setText("Cables");
        jMenu15.setFont(new java.awt.Font("UD Digi Kyokasho NK-B", 1, 12)); // NOI18N

        jMenu16.setText("Adaptadores");
        jMenu16.setFocusable(false);
        jMenu16.setFont(new java.awt.Font("UD Digi Kyokasho NK-B", 1, 12)); // NOI18N
        jMenu15.add(jMenu16);

        jMenu18.setText("Cables audio/video");
        jMenu18.setFocusable(false);
        jMenu18.setFont(new java.awt.Font("UD Digi Kyokasho NK-B", 1, 12)); // NOI18N
        jMenu15.add(jMenu18);

        jMenu20.setText("Cables HDMI");
        jMenu20.setFocusable(false);
        jMenu20.setFont(new java.awt.Font("UD Digi Kyokasho NK-B", 1, 12)); // NOI18N
        jMenu15.add(jMenu20);

        jMenu22.setText("Cables VGA");
        jMenu22.setFocusable(false);
        jMenu22.setFont(new java.awt.Font("UD Digi Kyokasho NK-B", 1, 12)); // NOI18N
        jMenu15.add(jMenu22);

        jMenu23.setText("Cables USB");
        jMenu23.setFocusable(false);
        jMenu23.setFont(new java.awt.Font("UD Digi Kyokasho NK-B", 1, 12)); // NOI18N
        jMenu15.add(jMenu23);

        jMenu6.add(jMenu15);

        jMenu3.add(jMenu6);

        jMenu38.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/house-2.png"))); // NOI18N
        jMenu38.setText("Ferreteria");
        jMenu38.setFocusable(false);
        jMenu38.setFont(new java.awt.Font("UD Digi Kyokasho NK-B", 1, 12)); // NOI18N

        jMenu39.setText("Herramientas");
        jMenu39.setFont(new java.awt.Font("UD Digi Kyokasho NK-B", 1, 12)); // NOI18N

        jMenu40.setText("Taladros");
        jMenu40.setFont(new java.awt.Font("UD Digi Kyokasho NK-B", 1, 12)); // NOI18N
        jMenu39.add(jMenu40);

        jMenu41.setText("Martillos perforadores");
        jMenu41.setFont(new java.awt.Font("UD Digi Kyokasho NK-B", 1, 12)); // NOI18N
        jMenu39.add(jMenu41);

        jMenu50.setText("Atornilladores");
        jMenu50.setFont(new java.awt.Font("UD Digi Kyokasho NK-B", 1, 12)); // NOI18N
        jMenu39.add(jMenu50);

        jMenu51.setText("Destornilladores electricos");
        jMenu51.setFont(new java.awt.Font("UD Digi Kyokasho NK-B", 1, 12)); // NOI18N
        jMenu39.add(jMenu51);

        jMenu52.setText("Kits de herramientas");
        jMenu52.setFont(new java.awt.Font("UD Digi Kyokasho NK-B", 1, 12)); // NOI18N
        jMenu39.add(jMenu52);

        jMenu38.add(jMenu39);

        jMenu42.setText("De estructura");
        jMenu42.setFont(new java.awt.Font("UD Digi Kyokasho NK-B", 1, 12)); // NOI18N

        jMenu43.setText("Anclajes");
        jMenu43.setFont(new java.awt.Font("UD Digi Kyokasho NK-B", 1, 12)); // NOI18N
        jMenu42.add(jMenu43);

        jMenu44.setText("Perfiles");
        jMenu44.setFont(new java.awt.Font("UD Digi Kyokasho NK-B", 1, 12)); // NOI18N
        jMenu42.add(jMenu44);

        jMenu45.setText("Soporte");
        jMenu45.setFont(new java.awt.Font("UD Digi Kyokasho NK-B", 1, 12)); // NOI18N
        jMenu42.add(jMenu45);

        jMenu38.add(jMenu42);

        jMenu3.add(jMenu38);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Contactenos");
        jMenu4.setFont(new java.awt.Font("UD Digi Kyokasho NK-B", 1, 12)); // NOI18N

        jMenu46.setText("Sobre nosotros");
        jMenu46.setFont(new java.awt.Font("UD Digi Kyokasho NK-B", 1, 12)); // NOI18N
        jMenu4.add(jMenu46);

        jMenu47.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img2/call.png"))); // NOI18N
        jMenu47.setText("Detalles de contacto");
        jMenu47.setFont(new java.awt.Font("UD Digi Kyokasho NK-B", 1, 12)); // NOI18N
        jMenu4.add(jMenu47);

        jMenuBar1.add(jMenu4);

        jMenu5.setText("Login");
        jMenu5.setFont(new java.awt.Font("UD Digi Kyokasho NK-B", 1, 12)); // NOI18N

        jMenu48.setText("Unetenos");
        jMenu48.setFont(new java.awt.Font("UD Digi Kyokasho NK-B", 1, 12)); // NOI18N

        jMenu53.setText("Como vendedor");
        jMenu53.setFont(new java.awt.Font("UD Digi Kyokasho NK-B", 1, 12)); // NOI18N
        jMenu48.add(jMenu53);

        jMenu54.setText("Como cliente");
        jMenu54.setFont(new java.awt.Font("UD Digi Kyokasho NK-B", 1, 12)); // NOI18N
        jMenu48.add(jMenu54);

        jMenu5.add(jMenu48);

        jMenu49.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img2/profile-circle.png"))); // NOI18N
        jMenu49.setText("Inicia sesión");
        jMenu49.setFont(new java.awt.Font("UD Digi Kyokasho NK-B", 1, 12)); // NOI18N
        jMenu5.add(jMenu49);

        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 936, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 879, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton14ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Producto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Producto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Producto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Producto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Producto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JMenu jMenu10;
    private javax.swing.JMenu jMenu11;
    private javax.swing.JMenu jMenu12;
    private javax.swing.JMenu jMenu13;
    private javax.swing.JMenu jMenu14;
    private javax.swing.JMenu jMenu15;
    private javax.swing.JMenu jMenu16;
    private javax.swing.JMenu jMenu17;
    private javax.swing.JMenu jMenu18;
    private javax.swing.JMenu jMenu19;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu20;
    private javax.swing.JMenu jMenu21;
    private javax.swing.JMenu jMenu22;
    private javax.swing.JMenu jMenu23;
    private javax.swing.JMenu jMenu24;
    private javax.swing.JMenu jMenu25;
    private javax.swing.JMenu jMenu26;
    private javax.swing.JMenu jMenu27;
    private javax.swing.JMenu jMenu28;
    private javax.swing.JMenu jMenu29;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu30;
    private javax.swing.JMenu jMenu31;
    private javax.swing.JMenu jMenu32;
    private javax.swing.JMenu jMenu33;
    private javax.swing.JMenu jMenu34;
    private javax.swing.JMenu jMenu35;
    private javax.swing.JMenu jMenu36;
    private javax.swing.JMenu jMenu37;
    private javax.swing.JMenu jMenu38;
    private javax.swing.JMenu jMenu39;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu40;
    private javax.swing.JMenu jMenu41;
    private javax.swing.JMenu jMenu42;
    private javax.swing.JMenu jMenu43;
    private javax.swing.JMenu jMenu44;
    private javax.swing.JMenu jMenu45;
    private javax.swing.JMenu jMenu46;
    private javax.swing.JMenu jMenu47;
    private javax.swing.JMenu jMenu48;
    private javax.swing.JMenu jMenu49;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu50;
    private javax.swing.JMenu jMenu51;
    private javax.swing.JMenu jMenu52;
    private javax.swing.JMenu jMenu53;
    private javax.swing.JMenu jMenu54;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu78;
    private javax.swing.JMenu jMenu79;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenu jMenu80;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jSpinner2;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
