/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frontend;

/**
 *
 * @author BOG-A307-E-016
 */
public class Registro_usuario extends javax.swing.JFrame {

    /**
     * Creates new form Frm_Pr
     */
    public Registro_usuario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jFrame1 = new javax.swing.JFrame();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        jPopupMenu2 = new javax.swing.JPopupMenu();
        jFileChooser1 = new javax.swing.JFileChooser();
        jPanel1 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        direc = new javax.swing.JLabel();
        dirs = new javax.swing.JTextField();
        foto = new javax.swing.JLabel();
        fechanacimiento = new javax.swing.JLabel();
        vercontras = new javax.swing.JTextField();
        apellidos = new javax.swing.JTextField();
        id = new javax.swing.JLabel();
        correos = new javax.swing.JTextField();
        numtel = new javax.swing.JLabel();
        fechas = new javax.swing.JTextField();
        correo = new javax.swing.JLabel();
        idusuarios = new javax.swing.JTextField();
        jButton7 = new javax.swing.JButton();
        registro = new javax.swing.JButton();
        facebook = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        autorizacion = new javax.swing.JCheckBox();
        google = new javax.swing.JButton();
        ids = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        contraseña = new javax.swing.JLabel();
        contras = new javax.swing.JTextField();
        vercontra = new javax.swing.JLabel();
        apellido = new javax.swing.JLabel();
        idusuario = new javax.swing.JLabel();
        nombre = new javax.swing.JLabel();
        nombres = new javax.swing.JTextField();
        tipoids = new javax.swing.JComboBox<>();
        tipoid = new javax.swing.JLabel();
        tipousuario = new javax.swing.JLabel();
        fotos = new javax.swing.JFileChooser();
        tels = new javax.swing.JTextField();
        tipus = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        jMenu7 = new javax.swing.JMenu();
        jMenu8 = new javax.swing.JMenu();
        jMenu31 = new javax.swing.JMenu();
        jMenu32 = new javax.swing.JMenu();
        jMenu9 = new javax.swing.JMenu();
        jMenu10 = new javax.swing.JMenu();
        jMenu30 = new javax.swing.JMenu();
        jMenu33 = new javax.swing.JMenu();
        jMenu34 = new javax.swing.JMenu();
        jMenu35 = new javax.swing.JMenu();
        jMenu36 = new javax.swing.JMenu();
        jMenu37 = new javax.swing.JMenu();
        jMenu24 = new javax.swing.JMenu();
        jMenu25 = new javax.swing.JMenu();
        jMenu26 = new javax.swing.JMenu();
        jMenu27 = new javax.swing.JMenu();
        jMenu28 = new javax.swing.JMenu();
        jMenu29 = new javax.swing.JMenu();
        jMenu17 = new javax.swing.JMenu();
        jMenu19 = new javax.swing.JMenu();
        jMenu21 = new javax.swing.JMenu();
        jMenu78 = new javax.swing.JMenu();
        jMenu79 = new javax.swing.JMenu();
        jMenu80 = new javax.swing.JMenu();
        jMenu11 = new javax.swing.JMenu();
        jMenu12 = new javax.swing.JMenu();
        jMenu13 = new javax.swing.JMenu();
        jMenu14 = new javax.swing.JMenu();
        jMenu15 = new javax.swing.JMenu();
        jMenu16 = new javax.swing.JMenu();
        jMenu18 = new javax.swing.JMenu();
        jMenu20 = new javax.swing.JMenu();
        jMenu22 = new javax.swing.JMenu();
        jMenu23 = new javax.swing.JMenu();
        jMenu38 = new javax.swing.JMenu();
        jMenu39 = new javax.swing.JMenu();
        jMenu40 = new javax.swing.JMenu();
        jMenu41 = new javax.swing.JMenu();
        jMenu50 = new javax.swing.JMenu();
        jMenu51 = new javax.swing.JMenu();
        jMenu52 = new javax.swing.JMenu();
        jMenu42 = new javax.swing.JMenu();
        jMenu43 = new javax.swing.JMenu();
        jMenu44 = new javax.swing.JMenu();
        jMenu45 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenu46 = new javax.swing.JMenu();
        jMenu47 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jMenu48 = new javax.swing.JMenu();
        jMenu49 = new javax.swing.JMenu();

        jMenuItem1.setText("jMenuItem1");

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton3.setBackground(new java.awt.Color(255, 255, 255));
        jButton3.setFont(new java.awt.Font("UD Digi Kyokasho NK-B", 0, 12)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img2/Villa_Home_Icon_UIA.png"))); // NOI18N
        jButton3.setText("Inicio");
        jButton3.setBorder(null);
        jButton3.setContentAreaFilled(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 30, 120, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/logo2.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, -10, 210, 100));

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setFont(new java.awt.Font("UD Digi Kyokasho NK-B", 0, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img2/Cart_Icon_UIA.png"))); // NOI18N
        jButton2.setText("Tienda");
        jButton2.setBorder(null);
        jButton2.setContentAreaFilled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 30, 120, 30));

        jButton5.setBackground(new java.awt.Color(255, 255, 255));
        jButton5.setFont(new java.awt.Font("UD Digi Kyokasho NK-B", 0, 12)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img2/profile-circle.png"))); // NOI18N
        jButton5.setText("Login");
        jButton5.setBorder(null);
        jButton5.setContentAreaFilled(false);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 30, 120, 30));

        jButton6.setBackground(new java.awt.Color(255, 255, 255));
        jButton6.setFont(new java.awt.Font("UD Digi Kyokasho NK-B", 0, 12)); // NOI18N
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img2/call.png"))); // NOI18N
        jButton6.setText("Contactenos");
        jButton6.setBorder(null);
        jButton6.setContentAreaFilled(false);
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 30, 120, 30));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("UD Digi Kyokasho NK-B", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(52, 52, 52));
        jLabel4.setText("Registre una cuenta individual");
        jPanel4.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 10, 330, 40));

        direc.setFont(new java.awt.Font("UD Digi Kyokasho NK-B", 1, 12)); // NOI18N
        direc.setText("Dirección de residencia*");
        jPanel4.add(direc, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 270, -1, -1));

        dirs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dirsActionPerformed(evt);
            }
        });
        jPanel4.add(dirs, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 290, 210, 30));

        foto.setFont(new java.awt.Font("UD Digi Kyokasho NK-B", 1, 12)); // NOI18N
        foto.setText("Cargar foto");
        jPanel4.add(foto, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 80, -1, -1));

        fechanacimiento.setFont(new java.awt.Font("UD Digi Kyokasho NK-B", 1, 12)); // NOI18N
        fechanacimiento.setText("Fecha de Nacimiento*");
        jPanel4.add(fechanacimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 270, -1, -1));

        vercontras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vercontrasActionPerformed(evt);
            }
        });
        jPanel4.add(vercontras, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 420, 210, 30));

        apellidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                apellidosActionPerformed(evt);
            }
        });
        jPanel4.add(apellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 160, 210, 30));

        id.setFont(new java.awt.Font("UD Digi Kyokasho NK-B", 1, 12)); // NOI18N
        id.setText("Identificación*");
        jPanel4.add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 340, -1, -1));

        correos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                correosActionPerformed(evt);
            }
        });
        jPanel4.add(correos, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, 210, 30));

        numtel.setFont(new java.awt.Font("UD Digi Kyokasho NK-B", 1, 12)); // NOI18N
        numtel.setText("Número de telefono*");
        jPanel4.add(numtel, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 200, -1, -1));

        fechas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fechasActionPerformed(evt);
            }
        });
        jPanel4.add(fechas, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 290, 210, 30));

        correo.setFont(new java.awt.Font("UD Digi Kyokasho NK-B", 1, 12)); // NOI18N
        correo.setText("Correo electronico*");
        jPanel4.add(correo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, -1, -1));

        idusuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idusuariosActionPerformed(evt);
            }
        });
        jPanel4.add(idusuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, 210, 30));

        jButton7.setBackground(new java.awt.Color(64, 82, 174));
        jButton7.setFont(new java.awt.Font("UD Digi Kyokasho NK-B", 0, 12)); // NOI18N
        jButton7.setForeground(new java.awt.Color(120, 121, 241));
        jButton7.setText("Terminos y condiciones");
        jButton7.setBorder(null);
        jButton7.setContentAreaFilled(false);
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 290, 180, 30));

        registro.setBackground(new java.awt.Color(65, 83, 175));
        registro.setFont(new java.awt.Font("UD Digi Kyokasho NK-B", 0, 12)); // NOI18N
        registro.setForeground(new java.awt.Color(255, 255, 255));
        registro.setText("Registrarse");
        registro.setBorder(null);
        registro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registroActionPerformed(evt);
            }
        });
        jPanel4.add(registro, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 390, 210, 30));

        facebook.setBackground(new java.awt.Color(64, 82, 174));
        facebook.setFont(new java.awt.Font("UD Digi Kyokasho NK-B", 0, 12)); // NOI18N
        facebook.setForeground(new java.awt.Color(64, 82, 174));
        facebook.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Facebook.png"))); // NOI18N
        facebook.setText("Facebook");
        facebook.setBorder(null);
        facebook.setContentAreaFilled(false);
        facebook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                facebookActionPerformed(evt);
            }
        });
        jPanel4.add(facebook, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 350, 120, 30));

        jLabel8.setFont(new java.awt.Font("UD Digi Kyokasho NK-B", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(102, 102, 102));
        jLabel8.setText("Complete el formulario con sus datos");
        jPanel4.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, -1, -1));

        autorizacion.setFont(new java.awt.Font("UD Digi Kyokasho NK-B", 1, 12)); // NOI18N
        autorizacion.setText("Autorizo el uso de mis datos en los siguientes");
        autorizacion.setBorder(null);
        autorizacion.setContentAreaFilled(false);
        autorizacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                autorizacionActionPerformed(evt);
            }
        });
        jPanel4.add(autorizacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 280, -1, -1));

        google.setBackground(new java.awt.Color(64, 82, 174));
        google.setFont(new java.awt.Font("UD Digi Kyokasho NK-B", 0, 12)); // NOI18N
        google.setForeground(new java.awt.Color(64, 82, 174));
        google.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Google.png"))); // NOI18N
        google.setText("Google");
        google.setBorder(null);
        google.setContentAreaFilled(false);
        google.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                googleActionPerformed(evt);
            }
        });
        jPanel4.add(google, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 350, 120, 30));

        ids.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idsActionPerformed(evt);
            }
        });
        jPanel4.add(ids, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 360, 210, 30));

        jLabel14.setFont(new java.awt.Font("UD Digi Kyokasho NK-B", 1, 12)); // NOI18N
        jLabel14.setText("____________Enlazar cuenta con____________");
        jPanel4.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 330, -1, -1));

        contraseña.setFont(new java.awt.Font("UD Digi Kyokasho NK-B", 1, 12)); // NOI18N
        contraseña.setText("Contraseña*");
        jPanel4.add(contraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 400, -1, -1));

        contras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contrasActionPerformed(evt);
            }
        });
        jPanel4.add(contras, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 420, 210, 30));

        vercontra.setFont(new java.awt.Font("UD Digi Kyokasho NK-B", 1, 12)); // NOI18N
        vercontra.setText("Verificar contraseña*");
        jPanel4.add(vercontra, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 400, -1, -1));

        apellido.setFont(new java.awt.Font("UD Digi Kyokasho NK-B", 1, 12)); // NOI18N
        apellido.setText("Apellidos*");
        jPanel4.add(apellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 140, 70, -1));

        idusuario.setFont(new java.awt.Font("UD Digi Kyokasho NK-B", 1, 12)); // NOI18N
        idusuario.setText("Id Usuario*");
        jPanel4.add(idusuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, -1, -1));

        nombre.setFont(new java.awt.Font("UD Digi Kyokasho NK-B", 1, 12)); // NOI18N
        nombre.setText("Nombres*");
        jPanel4.add(nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, 70, -1));

        nombres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombresActionPerformed(evt);
            }
        });
        jPanel4.add(nombres, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, 210, 30));

        tipoids.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        tipoids.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tipoidsActionPerformed(evt);
            }
        });
        jPanel4.add(tipoids, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 360, 210, 30));

        tipoid.setFont(new java.awt.Font("UD Digi Kyokasho NK-B", 1, 12)); // NOI18N
        tipoid.setText("Tipo de identificación*");
        jPanel4.add(tipoid, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 340, -1, -1));

        tipousuario.setFont(new java.awt.Font("UD Digi Kyokasho NK-B", 1, 12)); // NOI18N
        tipousuario.setText("Tipo de Usuario*");
        jPanel4.add(tipousuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 80, -1, -1));
        jPanel4.add(fotos, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 90, 260, 170));

        tels.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                telsActionPerformed(evt);
            }
        });
        jPanel4.add(tels, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 220, 210, 30));

        tipus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        tipus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tipusActionPerformed(evt);
            }
        });
        jPanel4.add(tipus, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 100, 210, 30));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, 890, 620));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Vector.png"))); // NOI18N
        jLabel3.setText("jLabel3");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 230));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 1040, 830));

        jMenuBar1.setBorder(null);
        jMenuBar1.setFont(new java.awt.Font("UD Digi Kyokasho NK-B", 1, 12)); // NOI18N

        jMenu2.setText("Inicio");
        jMenu2.setFont(new java.awt.Font("UD Digi Kyokasho NK-B", 1, 12)); // NOI18N
        jMenuBar1.add(jMenu2);

        jMenu3.setText("Tienda");
        jMenu3.setFont(new java.awt.Font("UD Digi Kyokasho NK-B", 1, 12)); // NOI18N

        jMenu6.setText("Tecnologia");
        jMenu6.setFont(new java.awt.Font("UD Digi Kyokasho NK-B", 1, 12)); // NOI18N

        jMenu7.setText("Ordenadores");
        jMenu7.setFocusable(false);
        jMenu7.setFont(new java.awt.Font("UD Digi Kyokasho NK-B", 1, 12)); // NOI18N

        jMenu8.setText("Portatiles");
        jMenu8.setFont(new java.awt.Font("UD Digi Kyokasho NK-B", 1, 12)); // NOI18N

        jMenu31.setText("Gaming");
        jMenu31.setFont(new java.awt.Font("UD Digi Kyokasho NK-B", 1, 12)); // NOI18N
        jMenu8.add(jMenu31);

        jMenu32.setText("Baratos");
        jMenu32.setFont(new java.awt.Font("UD Digi Kyokasho NK-B", 1, 12)); // NOI18N
        jMenu8.add(jMenu32);

        jMenu7.add(jMenu8);

        jMenu9.setText("PC sobre mesa");
        jMenu9.setFont(new java.awt.Font("UD Digi Kyokasho NK-B", 1, 12)); // NOI18N

        jMenu10.setText("PC gaming");
        jMenu10.setFont(new java.awt.Font("UD Digi Kyokasho NK-B", 1, 12)); // NOI18N
        jMenu9.add(jMenu10);

        jMenu30.setText("PC todo en uno");
        jMenu30.setFont(new java.awt.Font("UD Digi Kyokasho NK-B", 1, 12)); // NOI18N
        jMenu9.add(jMenu30);

        jMenu7.add(jMenu9);

        jMenu33.setText("Por marca");
        jMenu33.setFont(new java.awt.Font("UD Digi Kyokasho NK-B", 1, 12)); // NOI18N

        jMenu34.setText("Hp");
        jMenu34.setFont(new java.awt.Font("UD Digi Kyokasho NK-B", 1, 12)); // NOI18N
        jMenu33.add(jMenu34);

        jMenu35.setText("Lenovo");
        jMenu35.setFont(new java.awt.Font("UD Digi Kyokasho NK-B", 1, 12)); // NOI18N
        jMenu33.add(jMenu35);

        jMenu36.setText("Asus");
        jMenu36.setFont(new java.awt.Font("UD Digi Kyokasho NK-B", 1, 12)); // NOI18N
        jMenu33.add(jMenu36);

        jMenu37.setText("Acer");
        jMenu37.setFont(new java.awt.Font("UD Digi Kyokasho NK-B", 1, 12)); // NOI18N
        jMenu33.add(jMenu37);

        jMenu7.add(jMenu33);

        jMenu6.add(jMenu7);

        jMenu24.setText("Componentes");
        jMenu24.setFont(new java.awt.Font("UD Digi Kyokasho NK-B", 1, 12)); // NOI18N

        jMenu25.setText("Placas base");
        jMenu25.setFocusable(false);
        jMenu25.setFont(new java.awt.Font("UD Digi Kyokasho NK-B", 1, 12)); // NOI18N
        jMenu24.add(jMenu25);

        jMenu26.setText("Procesadores");
        jMenu26.setFocusable(false);
        jMenu26.setFont(new java.awt.Font("UD Digi Kyokasho NK-B", 1, 12)); // NOI18N
        jMenu24.add(jMenu26);

        jMenu27.setText("Discos duros");
        jMenu27.setFocusable(false);
        jMenu27.setFont(new java.awt.Font("UD Digi Kyokasho NK-B", 1, 12)); // NOI18N
        jMenu24.add(jMenu27);

        jMenu28.setText("Tarjetas gráficas");
        jMenu28.setFocusable(false);
        jMenu28.setFont(new java.awt.Font("UD Digi Kyokasho NK-B", 1, 12)); // NOI18N
        jMenu24.add(jMenu28);

        jMenu29.setText("Memoria RAM");
        jMenu29.setFocusable(false);
        jMenu29.setFont(new java.awt.Font("UD Digi Kyokasho NK-B", 1, 12)); // NOI18N
        jMenu24.add(jMenu29);

        jMenu6.add(jMenu24);

        jMenu17.setText("Perifericos");
        jMenu17.setFont(new java.awt.Font("UD Digi Kyokasho NK-B", 1, 12)); // NOI18N

        jMenu19.setText("Monitores");
        jMenu19.setFocusable(false);
        jMenu19.setFont(new java.awt.Font("UD Digi Kyokasho NK-B", 1, 12)); // NOI18N
        jMenu17.add(jMenu19);

        jMenu21.setText("Teclados");
        jMenu21.setFocusable(false);
        jMenu21.setFont(new java.awt.Font("UD Digi Kyokasho NK-B", 1, 12)); // NOI18N
        jMenu17.add(jMenu21);

        jMenu78.setText("Ratones");
        jMenu78.setFocusable(false);
        jMenu78.setFont(new java.awt.Font("UD Digi Kyokasho NK-B", 1, 12)); // NOI18N
        jMenu17.add(jMenu78);

        jMenu79.setText("Auriculares");
        jMenu79.setFocusable(false);
        jMenu79.setFont(new java.awt.Font("UD Digi Kyokasho NK-B", 1, 12)); // NOI18N
        jMenu17.add(jMenu79);

        jMenu80.setText("Microfonos");
        jMenu80.setFocusable(false);
        jMenu80.setFont(new java.awt.Font("UD Digi Kyokasho NK-B", 1, 12)); // NOI18N
        jMenu17.add(jMenu80);

        jMenu6.add(jMenu17);

        jMenu11.setText("Almacenamiento");
        jMenu11.setFocusable(false);
        jMenu11.setFont(new java.awt.Font("UD Digi Kyokasho NK-B", 1, 12)); // NOI18N

        jMenu12.setText("Memorias USB");
        jMenu12.setFont(new java.awt.Font("UD Digi Kyokasho NK-B", 1, 12)); // NOI18N
        jMenu11.add(jMenu12);

        jMenu13.setText("Tarjetas de memoria");
        jMenu13.setFont(new java.awt.Font("UD Digi Kyokasho NK-B", 1, 12)); // NOI18N
        jMenu11.add(jMenu13);

        jMenu14.setText("Discos duros");
        jMenu14.setFont(new java.awt.Font("UD Digi Kyokasho NK-B", 1, 12)); // NOI18N
        jMenu11.add(jMenu14);

        jMenu6.add(jMenu11);

        jMenu15.setText("Cables");
        jMenu15.setFont(new java.awt.Font("UD Digi Kyokasho NK-B", 1, 12)); // NOI18N

        jMenu16.setText("Adaptadores");
        jMenu16.setFocusable(false);
        jMenu16.setFont(new java.awt.Font("UD Digi Kyokasho NK-B", 1, 12)); // NOI18N
        jMenu15.add(jMenu16);

        jMenu18.setText("Cables audio/video");
        jMenu18.setFocusable(false);
        jMenu18.setFont(new java.awt.Font("UD Digi Kyokasho NK-B", 1, 12)); // NOI18N
        jMenu15.add(jMenu18);

        jMenu20.setText("Cables HDMI");
        jMenu20.setFocusable(false);
        jMenu20.setFont(new java.awt.Font("UD Digi Kyokasho NK-B", 1, 12)); // NOI18N
        jMenu15.add(jMenu20);

        jMenu22.setText("Cables VGA");
        jMenu22.setFocusable(false);
        jMenu22.setFont(new java.awt.Font("UD Digi Kyokasho NK-B", 1, 12)); // NOI18N
        jMenu15.add(jMenu22);

        jMenu23.setText("Cables USB");
        jMenu23.setFocusable(false);
        jMenu23.setFont(new java.awt.Font("UD Digi Kyokasho NK-B", 1, 12)); // NOI18N
        jMenu15.add(jMenu23);

        jMenu6.add(jMenu15);

        jMenu3.add(jMenu6);

        jMenu38.setText("Ferreteria");
        jMenu38.setFocusable(false);
        jMenu38.setFont(new java.awt.Font("UD Digi Kyokasho NK-B", 1, 12)); // NOI18N

        jMenu39.setText("Herramientas");
        jMenu39.setFont(new java.awt.Font("UD Digi Kyokasho NK-B", 1, 12)); // NOI18N

        jMenu40.setText("Taladros");
        jMenu40.setFont(new java.awt.Font("UD Digi Kyokasho NK-B", 1, 12)); // NOI18N
        jMenu39.add(jMenu40);

        jMenu41.setText("Martillos perforadores");
        jMenu41.setFont(new java.awt.Font("UD Digi Kyokasho NK-B", 1, 12)); // NOI18N
        jMenu39.add(jMenu41);

        jMenu50.setText("Atornilladores");
        jMenu50.setFont(new java.awt.Font("UD Digi Kyokasho NK-B", 1, 12)); // NOI18N
        jMenu39.add(jMenu50);

        jMenu51.setText("Destornilladores electricos");
        jMenu51.setFont(new java.awt.Font("UD Digi Kyokasho NK-B", 1, 12)); // NOI18N
        jMenu39.add(jMenu51);

        jMenu52.setText("Kits de herramientas");
        jMenu52.setFont(new java.awt.Font("UD Digi Kyokasho NK-B", 1, 12)); // NOI18N
        jMenu39.add(jMenu52);

        jMenu38.add(jMenu39);

        jMenu42.setText("De estructura");
        jMenu42.setFont(new java.awt.Font("UD Digi Kyokasho NK-B", 1, 12)); // NOI18N

        jMenu43.setText("Anclajes");
        jMenu43.setFont(new java.awt.Font("UD Digi Kyokasho NK-B", 1, 12)); // NOI18N
        jMenu42.add(jMenu43);

        jMenu44.setText("Perfiles");
        jMenu44.setFont(new java.awt.Font("UD Digi Kyokasho NK-B", 1, 12)); // NOI18N
        jMenu42.add(jMenu44);

        jMenu45.setText("Soporte");
        jMenu45.setFont(new java.awt.Font("UD Digi Kyokasho NK-B", 1, 12)); // NOI18N
        jMenu42.add(jMenu45);

        jMenu38.add(jMenu42);

        jMenu3.add(jMenu38);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Contactenos");
        jMenu4.setFont(new java.awt.Font("UD Digi Kyokasho NK-B", 1, 12)); // NOI18N

        jMenu46.setText("Sobre nosotros");
        jMenu46.setFont(new java.awt.Font("UD Digi Kyokasho NK-B", 1, 12)); // NOI18N
        jMenu4.add(jMenu46);

        jMenu47.setText("Detalles de contacto");
        jMenu47.setFont(new java.awt.Font("UD Digi Kyokasho NK-B", 1, 12)); // NOI18N
        jMenu4.add(jMenu47);

        jMenuBar1.add(jMenu4);

        jMenu5.setText("Login");
        jMenu5.setFont(new java.awt.Font("UD Digi Kyokasho NK-B", 1, 12)); // NOI18N

        jMenu48.setText("Unetenos");
        jMenu48.setFont(new java.awt.Font("UD Digi Kyokasho NK-B", 1, 12)); // NOI18N
        jMenu5.add(jMenu48);

        jMenu49.setText("Inicia sesión");
        jMenu49.setFont(new java.awt.Font("UD Digi Kyokasho NK-B", 1, 12)); // NOI18N
        jMenu5.add(jMenu49);

        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void dirsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dirsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dirsActionPerformed

    private void facebookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_facebookActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_facebookActionPerformed

    private void registroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registroActionPerformed
        Frm_login registro=new  Frm_login();
        registro.setVisible(true);
        this.dispose(); 
    }//GEN-LAST:event_registroActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void vercontrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vercontrasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vercontrasActionPerformed

    private void correosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_correosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_correosActionPerformed

    private void fechasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fechasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fechasActionPerformed

    private void idusuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idusuariosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idusuariosActionPerformed

    private void autorizacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_autorizacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_autorizacionActionPerformed

    private void googleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_googleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_googleActionPerformed

    private void apellidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_apellidosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_apellidosActionPerformed

    private void idsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idsActionPerformed

    private void contrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contrasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_contrasActionPerformed

    private void nombresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombresActionPerformed

    private void tipoidsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tipoidsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tipoidsActionPerformed

    private void telsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_telsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_telsActionPerformed

    private void tipusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tipusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tipusActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registro_usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registro_usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registro_usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registro_usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registro_usuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel apellido;
    private javax.swing.JTextField apellidos;
    private javax.swing.JCheckBox autorizacion;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JTextField contras;
    private javax.swing.JLabel contraseña;
    private javax.swing.JLabel correo;
    private javax.swing.JTextField correos;
    private javax.swing.JLabel direc;
    private javax.swing.JTextField dirs;
    private javax.swing.JButton facebook;
    private javax.swing.JLabel fechanacimiento;
    private javax.swing.JTextField fechas;
    private javax.swing.JLabel foto;
    private javax.swing.JFileChooser fotos;
    private javax.swing.JButton google;
    private javax.swing.JLabel id;
    private javax.swing.JTextField ids;
    private javax.swing.JLabel idusuario;
    private javax.swing.JTextField idusuarios;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu10;
    private javax.swing.JMenu jMenu11;
    private javax.swing.JMenu jMenu12;
    private javax.swing.JMenu jMenu13;
    private javax.swing.JMenu jMenu14;
    private javax.swing.JMenu jMenu15;
    private javax.swing.JMenu jMenu16;
    private javax.swing.JMenu jMenu17;
    private javax.swing.JMenu jMenu18;
    private javax.swing.JMenu jMenu19;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu20;
    private javax.swing.JMenu jMenu21;
    private javax.swing.JMenu jMenu22;
    private javax.swing.JMenu jMenu23;
    private javax.swing.JMenu jMenu24;
    private javax.swing.JMenu jMenu25;
    private javax.swing.JMenu jMenu26;
    private javax.swing.JMenu jMenu27;
    private javax.swing.JMenu jMenu28;
    private javax.swing.JMenu jMenu29;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu30;
    private javax.swing.JMenu jMenu31;
    private javax.swing.JMenu jMenu32;
    private javax.swing.JMenu jMenu33;
    private javax.swing.JMenu jMenu34;
    private javax.swing.JMenu jMenu35;
    private javax.swing.JMenu jMenu36;
    private javax.swing.JMenu jMenu37;
    private javax.swing.JMenu jMenu38;
    private javax.swing.JMenu jMenu39;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu40;
    private javax.swing.JMenu jMenu41;
    private javax.swing.JMenu jMenu42;
    private javax.swing.JMenu jMenu43;
    private javax.swing.JMenu jMenu44;
    private javax.swing.JMenu jMenu45;
    private javax.swing.JMenu jMenu46;
    private javax.swing.JMenu jMenu47;
    private javax.swing.JMenu jMenu48;
    private javax.swing.JMenu jMenu49;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu50;
    private javax.swing.JMenu jMenu51;
    private javax.swing.JMenu jMenu52;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu78;
    private javax.swing.JMenu jMenu79;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenu jMenu80;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JPopupMenu jPopupMenu2;
    private javax.swing.JLabel nombre;
    private javax.swing.JTextField nombres;
    private javax.swing.JLabel numtel;
    private javax.swing.JButton registro;
    private javax.swing.JTextField tels;
    private javax.swing.JLabel tipoid;
    private javax.swing.JComboBox<String> tipoids;
    private javax.swing.JLabel tipousuario;
    private javax.swing.JComboBox<String> tipus;
    private javax.swing.JLabel vercontra;
    private javax.swing.JTextField vercontras;
    // End of variables declaration//GEN-END:variables
}
