/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frontend;

/**
 *
 * @author USER
 */
public class Tienda extends javax.swing.JFrame {

    /**
     * Creates new form Tienda
     */
    public Tienda() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jButton10 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        jButton20 = new javax.swing.JButton();
        jButton21 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jButton13 = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        jMenu7 = new javax.swing.JMenu();
        jMenu8 = new javax.swing.JMenu();
        jMenu31 = new javax.swing.JMenu();
        jMenu32 = new javax.swing.JMenu();
        jMenu9 = new javax.swing.JMenu();
        jMenu10 = new javax.swing.JMenu();
        jMenu30 = new javax.swing.JMenu();
        jMenu33 = new javax.swing.JMenu();
        jMenu34 = new javax.swing.JMenu();
        jMenu35 = new javax.swing.JMenu();
        jMenu36 = new javax.swing.JMenu();
        jMenu37 = new javax.swing.JMenu();
        jMenu24 = new javax.swing.JMenu();
        jMenu25 = new javax.swing.JMenu();
        jMenu26 = new javax.swing.JMenu();
        jMenu27 = new javax.swing.JMenu();
        jMenu28 = new javax.swing.JMenu();
        jMenu29 = new javax.swing.JMenu();
        jMenu17 = new javax.swing.JMenu();
        jMenu19 = new javax.swing.JMenu();
        jMenu21 = new javax.swing.JMenu();
        jMenu78 = new javax.swing.JMenu();
        jMenu79 = new javax.swing.JMenu();
        jMenu80 = new javax.swing.JMenu();
        jMenu11 = new javax.swing.JMenu();
        jMenu12 = new javax.swing.JMenu();
        jMenu13 = new javax.swing.JMenu();
        jMenu14 = new javax.swing.JMenu();
        jMenu15 = new javax.swing.JMenu();
        jMenu16 = new javax.swing.JMenu();
        jMenu18 = new javax.swing.JMenu();
        jMenu20 = new javax.swing.JMenu();
        jMenu22 = new javax.swing.JMenu();
        jMenu23 = new javax.swing.JMenu();
        jMenu38 = new javax.swing.JMenu();
        jMenu39 = new javax.swing.JMenu();
        jMenu40 = new javax.swing.JMenu();
        jMenu41 = new javax.swing.JMenu();
        jMenu50 = new javax.swing.JMenu();
        jMenu51 = new javax.swing.JMenu();
        jMenu52 = new javax.swing.JMenu();
        jMenu42 = new javax.swing.JMenu();
        jMenu43 = new javax.swing.JMenu();
        jMenu44 = new javax.swing.JMenu();
        jMenu45 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenu46 = new javax.swing.JMenu();
        jMenu47 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jMenu48 = new javax.swing.JMenu();
        jMenu53 = new javax.swing.JMenu();
        jMenu54 = new javax.swing.JMenu();
        jMenu49 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img2/Promocion.png"))); // NOI18N
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 230, -1, -1));

        jButton3.setBackground(new java.awt.Color(255, 255, 255));
        jButton3.setFont(new java.awt.Font("UD Digi Kyokasho NK-B", 0, 12)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img2/Villa_Home_Icon_UIA.png"))); // NOI18N
        jButton3.setText("Inicio");
        jButton3.setBorder(null);
        jButton3.setContentAreaFilled(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 30, 120, 30));

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setFont(new java.awt.Font("UD Digi Kyokasho NK-B", 0, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img2/Cart_Icon_UIA.png"))); // NOI18N
        jButton2.setText("Tienda");
        jButton2.setBorder(null);
        jButton2.setContentAreaFilled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 30, 120, 30));

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img2/Raton gaming.png"))); // NOI18N
        jButton4.setBorder(null);
        jButton4.setBorderPainted(false);
        jButton4.setContentAreaFilled(false);
        jButton4.setDefaultCapable(false);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 260, -1, -1));

        jLabel19.setBackground(new java.awt.Color(255, 255, 255));
        jLabel19.setFont(new java.awt.Font("UD Digi Kyokasho NK-B", 1, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(52, 52, 52));
        jLabel19.setText("FERRETERIA");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 490, 210, 40));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img2/Promocion.png"))); // NOI18N
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 230, -1, -1));

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img2/Promocion.png"))); // NOI18N
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 520, -1, -1));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img2/Promocion.png"))); // NOI18N
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, -1, -1));

        jButton5.setBackground(new java.awt.Color(255, 255, 255));
        jButton5.setFont(new java.awt.Font("UD Digi Kyokasho NK-B", 0, 12)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img2/profile-circle.png"))); // NOI18N
        jButton5.setText("Login");
        jButton5.setBorder(null);
        jButton5.setContentAreaFilled(false);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 30, 120, 30));

        jButton6.setBackground(new java.awt.Color(255, 255, 255));
        jButton6.setFont(new java.awt.Font("UD Digi Kyokasho NK-B", 0, 12)); // NOI18N
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img2/call.png"))); // NOI18N
        jButton6.setText("Contactenos");
        jButton6.setBorder(null);
        jButton6.setContentAreaFilled(false);
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 30, 120, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Logo.jpg"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, -1));

        jLabel12.setFont(new java.awt.Font("UD Digi Kyokasho NK-B", 1, 12)); // NOI18N
        jLabel12.setText("Tempest X20W Vigilant Ratón Gaming Inalámbrico");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 460, 240, 30));

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setFont(new java.awt.Font("UD Digi Kyokasho NK-B", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(52, 52, 52));
        jLabel11.setText("TECNOLOGIA");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 210, 40));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Vector2.png"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(-100, -10, -1, 240));

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton10.setBackground(new java.awt.Color(64, 82, 174));
        jButton10.setFont(new java.awt.Font("UD Digi Kyokasho NK-B", 0, 12)); // NOI18N
        jButton10.setForeground(new java.awt.Color(255, 255, 255));
        jButton10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/house-2.png"))); // NOI18N
        jButton10.setText("Ferreteria");
        jButton10.setBorder(null);
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 200, 30));

        jButton15.setBackground(new java.awt.Color(64, 82, 174));
        jButton15.setFont(new java.awt.Font("UD Digi Kyokasho NK-B", 0, 12)); // NOI18N
        jButton15.setForeground(new java.awt.Color(64, 82, 174));
        jButton15.setText("Cables");
        jButton15.setBorder(null);
        jButton15.setContentAreaFilled(false);
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton15, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, 120, 20));

        jButton16.setBackground(new java.awt.Color(64, 82, 174));
        jButton16.setFont(new java.awt.Font("UD Digi Kyokasho NK-B", 0, 12)); // NOI18N
        jButton16.setForeground(new java.awt.Color(64, 82, 174));
        jButton16.setText("De estructura");
        jButton16.setBorder(null);
        jButton16.setContentAreaFilled(false);
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton16, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, 120, 20));

        jButton17.setBackground(new java.awt.Color(64, 82, 174));
        jButton17.setFont(new java.awt.Font("UD Digi Kyokasho NK-B", 0, 12)); // NOI18N
        jButton17.setForeground(new java.awt.Color(64, 82, 174));
        jButton17.setText("Componentes");
        jButton17.setBorder(null);
        jButton17.setContentAreaFilled(false);
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton17, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 120, 20));

        jButton18.setBackground(new java.awt.Color(64, 82, 174));
        jButton18.setFont(new java.awt.Font("UD Digi Kyokasho NK-B", 0, 12)); // NOI18N
        jButton18.setForeground(new java.awt.Color(64, 82, 174));
        jButton18.setText("Perifericos");
        jButton18.setBorder(null);
        jButton18.setContentAreaFilled(false);
        jButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton18ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton18, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 120, 20));

        jButton19.setBackground(new java.awt.Color(64, 82, 174));
        jButton19.setFont(new java.awt.Font("UD Digi Kyokasho NK-B", 0, 12)); // NOI18N
        jButton19.setForeground(new java.awt.Color(64, 82, 174));
        jButton19.setText("Almacenamiento");
        jButton19.setBorder(null);
        jButton19.setContentAreaFilled(false);
        jButton19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton19ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton19, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 120, 20));

        jButton20.setBackground(new java.awt.Color(64, 82, 174));
        jButton20.setFont(new java.awt.Font("UD Digi Kyokasho NK-B", 0, 12)); // NOI18N
        jButton20.setForeground(new java.awt.Color(64, 82, 174));
        jButton20.setText("Ordenadores");
        jButton20.setBorder(null);
        jButton20.setContentAreaFilled(false);
        jButton20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton20ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton20, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 120, 20));

        jButton21.setBackground(new java.awt.Color(64, 82, 174));
        jButton21.setFont(new java.awt.Font("UD Digi Kyokasho NK-B", 0, 12)); // NOI18N
        jButton21.setForeground(new java.awt.Color(64, 82, 174));
        jButton21.setText("Herramientas");
        jButton21.setBorder(null);
        jButton21.setContentAreaFilled(false);
        jButton21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton21ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton21, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, 120, 20));

        jButton9.setBackground(new java.awt.Color(64, 82, 174));
        jButton9.setFont(new java.awt.Font("UD Digi Kyokasho NK-B", 0, 12)); // NOI18N
        jButton9.setForeground(new java.awt.Color(255, 255, 255));
        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img2/cpu.png"))); // NOI18N
        jButton9.setText("Tecnologia");
        jButton9.setBorder(null);
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 200, 30));

        jLabel17.setBackground(new java.awt.Color(255, 255, 255));
        jLabel17.setFont(new java.awt.Font("UD Digi Kyokasho NK-B", 1, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(52, 52, 52));
        jLabel17.setText("Categorias");
        jPanel2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 210, 40));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 230, 200, 330));

        jLabel13.setFont(new java.awt.Font("UD Digi Kyokasho NK-B", 1, 12)); // NOI18N
        jLabel13.setText("Lenovo V14 G2 ITL Intel Core i5-1135G7/8GB/256GB SSD/14\"");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 460, 270, 30));

        jLabel14.setFont(new java.awt.Font("UD Digi Kyokasho NK-B", 1, 12)); // NOI18N
        jLabel14.setText("Taladro atornillador y perforador inalámbrico, batería litio 21V de 1.3Ah, velocidad 1500rpm, con batería, cargador y maletín incluidos - Greencut TD210L");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 750, 270, 30));

        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Taladro percutor.png"))); // NOI18N
        jButton7.setBorder(null);
        jButton7.setBorderPainted(false);
        jButton7.setContentAreaFilled(false);
        jButton7.setDefaultCapable(false);
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 540, 280, 210));

        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img2/Teclado mecanico.png"))); // NOI18N
        jButton8.setBorder(null);
        jButton8.setBorderPainted(false);
        jButton8.setContentAreaFilled(false);
        jButton8.setDefaultCapable(false);
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 270, -1, -1));

        jButton11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img2/Lenovo.png"))); // NOI18N
        jButton11.setBorder(null);
        jButton11.setBorderPainted(false);
        jButton11.setContentAreaFilled(false);
        jButton11.setDefaultCapable(false);
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, -1, -1));

        jButton12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img2/Taladro atornillador.png"))); // NOI18N
        jButton12.setBorder(null);
        jButton12.setBorderPainted(false);
        jButton12.setContentAreaFilled(false);
        jButton12.setDefaultCapable(false);
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 520, -1, -1));

        jLabel15.setFont(new java.awt.Font("UD Digi Kyokasho NK-B", 1, 12)); // NOI18N
        jLabel15.setText("1980W 3800rmp Taladro Percutor Multifucional, Herramienta Poderosa de Ferretería");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 750, 250, 30));

        jLabel16.setFont(new java.awt.Font("UD Digi Kyokasho NK-B", 1, 12)); // NOI18N
        jLabel16.setText("HP OMEN Sequencer Teclado Mecánico Gaming RGB Switch Blue");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 460, 250, 30));

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img2/Promocion.png"))); // NOI18N
        jPanel1.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 520, -1, -1));

        jButton13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img2/Amoladora angular.png"))); // NOI18N
        jButton13.setBorder(null);
        jButton13.setBorderPainted(false);
        jButton13.setContentAreaFilled(false);
        jButton13.setDefaultCapable(false);
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton13, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 530, 280, 210));

        jLabel21.setFont(new java.awt.Font("UD Digi Kyokasho NK-B", 1, 12)); // NOI18N
        jLabel21.setText("Amoladora angular Makita GA 4530 R - 720w 115mm");
        jPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 750, 250, 30));

        jScrollPane1.setViewportView(jPanel1);

        jMenuBar1.setBackground(new java.awt.Color(51, 51, 51));
        jMenuBar1.setBorder(null);
        jMenuBar1.setFont(new java.awt.Font("UD Digi Kyokasho NK-B", 1, 12)); // NOI18N

        jMenu2.setText("Inicio");
        jMenu2.setFont(new java.awt.Font("UD Digi Kyokasho NK-B", 1, 12)); // NOI18N
        jMenuBar1.add(jMenu2);

        jMenu3.setText("Tienda");
        jMenu3.setFont(new java.awt.Font("UD Digi Kyokasho NK-B", 1, 12)); // NOI18N

        jMenu6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img2/cpu.png"))); // NOI18N
        jMenu6.setText("Tecnologia");
        jMenu6.setFont(new java.awt.Font("UD Digi Kyokasho NK-B", 1, 12)); // NOI18N

        jMenu7.setText("Ordenadores");
        jMenu7.setFocusable(false);
        jMenu7.setFont(new java.awt.Font("UD Digi Kyokasho NK-B", 1, 12)); // NOI18N

        jMenu8.setText("Portatiles");
        jMenu8.setFont(new java.awt.Font("UD Digi Kyokasho NK-B", 1, 12)); // NOI18N

        jMenu31.setText("Gaming");
        jMenu31.setFont(new java.awt.Font("UD Digi Kyokasho NK-B", 1, 12)); // NOI18N
        jMenu8.add(jMenu31);

        jMenu32.setText("Baratos");
        jMenu32.setFont(new java.awt.Font("UD Digi Kyokasho NK-B", 1, 12)); // NOI18N
        jMenu8.add(jMenu32);

        jMenu7.add(jMenu8);

        jMenu9.setText("PC sobre mesa");
        jMenu9.setFont(new java.awt.Font("UD Digi Kyokasho NK-B", 1, 12)); // NOI18N

        jMenu10.setText("PC gaming");
        jMenu10.setFont(new java.awt.Font("UD Digi Kyokasho NK-B", 1, 12)); // NOI18N
        jMenu9.add(jMenu10);

        jMenu30.setText("PC todo en uno");
        jMenu30.setFont(new java.awt.Font("UD Digi Kyokasho NK-B", 1, 12)); // NOI18N
        jMenu9.add(jMenu30);

        jMenu7.add(jMenu9);

        jMenu33.setText("Por marca");
        jMenu33.setFont(new java.awt.Font("UD Digi Kyokasho NK-B", 1, 12)); // NOI18N

        jMenu34.setText("Hp");
        jMenu34.setFont(new java.awt.Font("UD Digi Kyokasho NK-B", 1, 12)); // NOI18N
        jMenu33.add(jMenu34);

        jMenu35.setText("Lenovo");
        jMenu35.setFont(new java.awt.Font("UD Digi Kyokasho NK-B", 1, 12)); // NOI18N
        jMenu33.add(jMenu35);

        jMenu36.setText("Asus");
        jMenu36.setFont(new java.awt.Font("UD Digi Kyokasho NK-B", 1, 12)); // NOI18N
        jMenu33.add(jMenu36);

        jMenu37.setText("Acer");
        jMenu37.setFont(new java.awt.Font("UD Digi Kyokasho NK-B", 1, 12)); // NOI18N
        jMenu33.add(jMenu37);

        jMenu7.add(jMenu33);

        jMenu6.add(jMenu7);

        jMenu24.setText("Componentes");
        jMenu24.setFont(new java.awt.Font("UD Digi Kyokasho NK-B", 1, 12)); // NOI18N

        jMenu25.setText("Placas base");
        jMenu25.setFocusable(false);
        jMenu25.setFont(new java.awt.Font("UD Digi Kyokasho NK-B", 1, 12)); // NOI18N
        jMenu24.add(jMenu25);

        jMenu26.setText("Procesadores");
        jMenu26.setFocusable(false);
        jMenu26.setFont(new java.awt.Font("UD Digi Kyokasho NK-B", 1, 12)); // NOI18N
        jMenu24.add(jMenu26);

        jMenu27.setText("Discos duros");
        jMenu27.setFocusable(false);
        jMenu27.setFont(new java.awt.Font("UD Digi Kyokasho NK-B", 1, 12)); // NOI18N
        jMenu24.add(jMenu27);

        jMenu28.setText("Tarjetas gráficas");
        jMenu28.setFocusable(false);
        jMenu28.setFont(new java.awt.Font("UD Digi Kyokasho NK-B", 1, 12)); // NOI18N
        jMenu24.add(jMenu28);

        jMenu29.setText("Memoria RAM");
        jMenu29.setFocusable(false);
        jMenu29.setFont(new java.awt.Font("UD Digi Kyokasho NK-B", 1, 12)); // NOI18N
        jMenu24.add(jMenu29);

        jMenu6.add(jMenu24);

        jMenu17.setText("Perifericos");
        jMenu17.setFont(new java.awt.Font("UD Digi Kyokasho NK-B", 1, 12)); // NOI18N

        jMenu19.setText("Monitores");
        jMenu19.setFocusable(false);
        jMenu19.setFont(new java.awt.Font("UD Digi Kyokasho NK-B", 1, 12)); // NOI18N
        jMenu17.add(jMenu19);

        jMenu21.setText("Teclados");
        jMenu21.setFocusable(false);
        jMenu21.setFont(new java.awt.Font("UD Digi Kyokasho NK-B", 1, 12)); // NOI18N
        jMenu17.add(jMenu21);

        jMenu78.setText("Ratones");
        jMenu78.setFocusable(false);
        jMenu78.setFont(new java.awt.Font("UD Digi Kyokasho NK-B", 1, 12)); // NOI18N
        jMenu17.add(jMenu78);

        jMenu79.setText("Auriculares");
        jMenu79.setFocusable(false);
        jMenu79.setFont(new java.awt.Font("UD Digi Kyokasho NK-B", 1, 12)); // NOI18N
        jMenu17.add(jMenu79);

        jMenu80.setText("Microfonos");
        jMenu80.setFocusable(false);
        jMenu80.setFont(new java.awt.Font("UD Digi Kyokasho NK-B", 1, 12)); // NOI18N
        jMenu17.add(jMenu80);

        jMenu6.add(jMenu17);

        jMenu11.setText("Almacenamiento");
        jMenu11.setFocusable(false);
        jMenu11.setFont(new java.awt.Font("UD Digi Kyokasho NK-B", 1, 12)); // NOI18N

        jMenu12.setText("Memorias USB");
        jMenu12.setFont(new java.awt.Font("UD Digi Kyokasho NK-B", 1, 12)); // NOI18N
        jMenu11.add(jMenu12);

        jMenu13.setText("Tarjetas de memoria");
        jMenu13.setFont(new java.awt.Font("UD Digi Kyokasho NK-B", 1, 12)); // NOI18N
        jMenu11.add(jMenu13);

        jMenu14.setText("Discos duros");
        jMenu14.setFont(new java.awt.Font("UD Digi Kyokasho NK-B", 1, 12)); // NOI18N
        jMenu11.add(jMenu14);

        jMenu6.add(jMenu11);

        jMenu15.setText("Cables");
        jMenu15.setFont(new java.awt.Font("UD Digi Kyokasho NK-B", 1, 12)); // NOI18N

        jMenu16.setText("Adaptadores");
        jMenu16.setFocusable(false);
        jMenu16.setFont(new java.awt.Font("UD Digi Kyokasho NK-B", 1, 12)); // NOI18N
        jMenu15.add(jMenu16);

        jMenu18.setText("Cables audio/video");
        jMenu18.setFocusable(false);
        jMenu18.setFont(new java.awt.Font("UD Digi Kyokasho NK-B", 1, 12)); // NOI18N
        jMenu15.add(jMenu18);

        jMenu20.setText("Cables HDMI");
        jMenu20.setFocusable(false);
        jMenu20.setFont(new java.awt.Font("UD Digi Kyokasho NK-B", 1, 12)); // NOI18N
        jMenu15.add(jMenu20);

        jMenu22.setText("Cables VGA");
        jMenu22.setFocusable(false);
        jMenu22.setFont(new java.awt.Font("UD Digi Kyokasho NK-B", 1, 12)); // NOI18N
        jMenu15.add(jMenu22);

        jMenu23.setText("Cables USB");
        jMenu23.setFocusable(false);
        jMenu23.setFont(new java.awt.Font("UD Digi Kyokasho NK-B", 1, 12)); // NOI18N
        jMenu15.add(jMenu23);

        jMenu6.add(jMenu15);

        jMenu3.add(jMenu6);

        jMenu38.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/house-2.png"))); // NOI18N
        jMenu38.setText("Ferreteria");
        jMenu38.setFocusable(false);
        jMenu38.setFont(new java.awt.Font("UD Digi Kyokasho NK-B", 1, 12)); // NOI18N

        jMenu39.setText("Herramientas");
        jMenu39.setFont(new java.awt.Font("UD Digi Kyokasho NK-B", 1, 12)); // NOI18N

        jMenu40.setText("Taladros");
        jMenu40.setFont(new java.awt.Font("UD Digi Kyokasho NK-B", 1, 12)); // NOI18N
        jMenu39.add(jMenu40);

        jMenu41.setText("Martillos perforadores");
        jMenu41.setFont(new java.awt.Font("UD Digi Kyokasho NK-B", 1, 12)); // NOI18N
        jMenu39.add(jMenu41);

        jMenu50.setText("Atornilladores");
        jMenu50.setFont(new java.awt.Font("UD Digi Kyokasho NK-B", 1, 12)); // NOI18N
        jMenu39.add(jMenu50);

        jMenu51.setText("Destornilladores electricos");
        jMenu51.setFont(new java.awt.Font("UD Digi Kyokasho NK-B", 1, 12)); // NOI18N
        jMenu39.add(jMenu51);

        jMenu52.setText("Kits de herramientas");
        jMenu52.setFont(new java.awt.Font("UD Digi Kyokasho NK-B", 1, 12)); // NOI18N
        jMenu39.add(jMenu52);

        jMenu38.add(jMenu39);

        jMenu42.setText("De estructura");
        jMenu42.setFont(new java.awt.Font("UD Digi Kyokasho NK-B", 1, 12)); // NOI18N

        jMenu43.setText("Anclajes");
        jMenu43.setFont(new java.awt.Font("UD Digi Kyokasho NK-B", 1, 12)); // NOI18N
        jMenu42.add(jMenu43);

        jMenu44.setText("Perfiles");
        jMenu44.setFont(new java.awt.Font("UD Digi Kyokasho NK-B", 1, 12)); // NOI18N
        jMenu42.add(jMenu44);

        jMenu45.setText("Soporte");
        jMenu45.setFont(new java.awt.Font("UD Digi Kyokasho NK-B", 1, 12)); // NOI18N
        jMenu42.add(jMenu45);

        jMenu38.add(jMenu42);

        jMenu3.add(jMenu38);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Contactenos");
        jMenu4.setFont(new java.awt.Font("UD Digi Kyokasho NK-B", 1, 12)); // NOI18N

        jMenu46.setText("Sobre nosotros");
        jMenu46.setFont(new java.awt.Font("UD Digi Kyokasho NK-B", 1, 12)); // NOI18N
        jMenu4.add(jMenu46);

        jMenu47.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img2/call.png"))); // NOI18N
        jMenu47.setText("Detalles de contacto");
        jMenu47.setFont(new java.awt.Font("UD Digi Kyokasho NK-B", 1, 12)); // NOI18N
        jMenu4.add(jMenu47);

        jMenuBar1.add(jMenu4);

        jMenu5.setText("Login");
        jMenu5.setFont(new java.awt.Font("UD Digi Kyokasho NK-B", 1, 12)); // NOI18N

        jMenu48.setText("Unetenos");
        jMenu48.setFont(new java.awt.Font("UD Digi Kyokasho NK-B", 1, 12)); // NOI18N

        jMenu53.setText("Como vendedor");
        jMenu53.setFont(new java.awt.Font("UD Digi Kyokasho NK-B", 1, 12)); // NOI18N
        jMenu48.add(jMenu53);

        jMenu54.setText("Como cliente");
        jMenu54.setFont(new java.awt.Font("UD Digi Kyokasho NK-B", 1, 12)); // NOI18N
        jMenu48.add(jMenu54);

        jMenu5.add(jMenu48);

        jMenu49.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img2/profile-circle.png"))); // NOI18N
        jMenu49.setText("Inicia sesión");
        jMenu49.setFont(new java.awt.Font("UD Digi Kyokasho NK-B", 1, 12)); // NOI18N
        jMenu5.add(jMenu49);

        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1170, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 879, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton15ActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton16ActionPerformed

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton17ActionPerformed

    private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton18ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton18ActionPerformed

    private void jButton19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton19ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton19ActionPerformed

    private void jButton20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton20ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton20ActionPerformed

    private void jButton21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton21ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton21ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton13ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tienda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tienda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tienda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tienda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tienda().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu10;
    private javax.swing.JMenu jMenu11;
    private javax.swing.JMenu jMenu12;
    private javax.swing.JMenu jMenu13;
    private javax.swing.JMenu jMenu14;
    private javax.swing.JMenu jMenu15;
    private javax.swing.JMenu jMenu16;
    private javax.swing.JMenu jMenu17;
    private javax.swing.JMenu jMenu18;
    private javax.swing.JMenu jMenu19;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu20;
    private javax.swing.JMenu jMenu21;
    private javax.swing.JMenu jMenu22;
    private javax.swing.JMenu jMenu23;
    private javax.swing.JMenu jMenu24;
    private javax.swing.JMenu jMenu25;
    private javax.swing.JMenu jMenu26;
    private javax.swing.JMenu jMenu27;
    private javax.swing.JMenu jMenu28;
    private javax.swing.JMenu jMenu29;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu30;
    private javax.swing.JMenu jMenu31;
    private javax.swing.JMenu jMenu32;
    private javax.swing.JMenu jMenu33;
    private javax.swing.JMenu jMenu34;
    private javax.swing.JMenu jMenu35;
    private javax.swing.JMenu jMenu36;
    private javax.swing.JMenu jMenu37;
    private javax.swing.JMenu jMenu38;
    private javax.swing.JMenu jMenu39;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu40;
    private javax.swing.JMenu jMenu41;
    private javax.swing.JMenu jMenu42;
    private javax.swing.JMenu jMenu43;
    private javax.swing.JMenu jMenu44;
    private javax.swing.JMenu jMenu45;
    private javax.swing.JMenu jMenu46;
    private javax.swing.JMenu jMenu47;
    private javax.swing.JMenu jMenu48;
    private javax.swing.JMenu jMenu49;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu50;
    private javax.swing.JMenu jMenu51;
    private javax.swing.JMenu jMenu52;
    private javax.swing.JMenu jMenu53;
    private javax.swing.JMenu jMenu54;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu78;
    private javax.swing.JMenu jMenu79;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenu jMenu80;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
